insert into public.gym_enrichments (
  postal_code,
  facility_type,
  equipment,
  amenities,
  day_pass_price,
  membership_price
)
values
  ('548315', 'Gymnasium', ARRAY['Treadmill','Dumbbells','Bench Press','Cable Machine','Stationary Bike'], ARRAY['Changing Rooms','Showers','Lockers','Water Cooler'], 2.5, 90),
  ('548315', 'Swimming Pool', ARRAY[]::text[], ARRAY['Changing Rooms','Showers','Lockers'], 1.5, null),
  ('548390', 'Swimming Pool', ARRAY[]::text[], ARRAY['Changing Rooms','Showers','Lockers'], 2, null),
  ('548431', 'Swimming Pool', ARRAY[]::text[], ARRAY['Changing Rooms','Showers','Lockers'], 2.5, null),
  ('548432', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('548432', 'Swimming Pool', ARRAY[]::text[], ARRAY['Changing Rooms','Showers','Lockers'], 1.5, null),
  ('548540', 'Swimming Pool', ARRAY[]::text[], ARRAY['Changing Rooms','Showers','Lockers'], 2, null),
  ('548595', 'Badminton Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 5, null),
  ('548595', 'Basketball Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 6, null),
  ('548595', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('548595', 'Netball Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 3, null),
  ('548595', 'Shooting Range', ARRAY[]::text[], ARRAY['Water Cooler'], null, null),
  ('548595', 'Table tennis Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 5, null),
  ('548595', 'Volleyball Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 6, null),
  ('548595', 'Wall Climbing', ARRAY[]::text[], ARRAY['Water Cooler'], null, null),
  ('548922', 'Gymnasium', ARRAY['Treadmill','Dumbbells','Bench Press','Cable Machine','Stationary Bike'], ARRAY['Changing Rooms','Showers','Lockers','Water Cooler'], 2.5, 90),
  ('548926', 'Basketball Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 4, null),
  ('548926', 'Cricket Field / Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 5, null),
  ('548926', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('548926', 'Football Field', ARRAY[]::text[], ARRAY['Bleachers','Water Cooler','Toilets'], null, null),
  ('548926', 'Studio', ARRAY[]::text[], ARRAY['Water Cooler'], null, null),
  ('548926', 'Tennis Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 4, null),
  ('548943', 'Swimming Pool', ARRAY[]::text[], ARRAY['Changing Rooms','Showers','Lockers'], 2, null),
  ('549010', 'Swimming Pool', ARRAY[]::text[], ARRAY['Changing Rooms','Showers','Lockers'], 2.5, null),
  ('549018', 'Gymnasium', ARRAY['Treadmill','Dumbbells','Bench Press','Cable Machine','Stationary Bike'], ARRAY['Changing Rooms','Showers','Lockers','Water Cooler'], 6, 300),
  ('549018', 'Swimming Pool', ARRAY[]::text[], ARRAY['Changing Rooms','Showers','Lockers'], 1.5, null),
  ('549171', 'Gymnasium', ARRAY['Treadmill','Dumbbells','Bench Press','Cable Machine','Stationary Bike'], ARRAY['Changing Rooms','Showers','Lockers','Water Cooler'], 3, 120),
  ('549171', 'Swimming Pool', ARRAY[]::text[], ARRAY['Changing Rooms','Showers','Lockers'], 2.5, null),
  ('549338', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('549338', 'Swimming Pool', ARRAY[]::text[], ARRAY['Changing Rooms','Showers','Lockers'], 1.5, null),
  ('549340', 'Swimming Pool', ARRAY[]::text[], ARRAY['Changing Rooms','Showers','Lockers'], 2, null),
  ('549555', 'Gymnasium', ARRAY['Treadmill','Dumbbells','Bench Press','Cable Machine','Stationary Bike'], ARRAY['Changing Rooms','Showers','Lockers','Water Cooler'], 3, 120),
  ('549555', 'Swimming Pool', ARRAY[]::text[], ARRAY['Changing Rooms','Showers','Lockers'], 1, null),
  ('549576', 'Gymnasium', ARRAY['Treadmill','Dumbbells','Bench Press','Cable Machine','Stationary Bike'], ARRAY['Changing Rooms','Showers','Lockers','Water Cooler'], 5, 240),
  ('549576', 'Swimming Pool', ARRAY[]::text[], ARRAY['Changing Rooms','Showers','Lockers'], 2, null),
  ('549977', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('550105', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('550105', 'Futsal / Street Soccer Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 5, null),
  ('550119', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('550125', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('550135', 'Basketball Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 3, null),
  ('550135', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('550135', 'Jogging Track', ARRAY[]::text[], ARRAY['Bleachers','Water Cooler','Toilets'], null, null),
  ('550137', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('550144', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('550145', 'Jogging Track', ARRAY[]::text[], ARRAY['Bleachers','Water Cooler','Toilets'], null, null),
  ('550145', 'Petanque Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 4, null),
  ('550157', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('550206', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('550208', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('550210', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('550213', 'Badminton Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 4, null),
  ('550216', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('550222', 'Basketball Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 6, null),
  ('550223', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('550228', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('550230', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('550235', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('550236', 'Badminton Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 6, null),
  ('550236', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('550236', 'Petanque Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 3, null),
  ('550236', 'Sepak Takraw Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 4, null),
  ('550236', 'Volleyball Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 5, null),
  ('550240', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('550242', 'Badminton Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 8, null),
  ('550246', 'Badminton Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 3, null),
  ('550246', 'Sepak Takraw Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 4, null),
  ('550253', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('550253', 'Gymnasium', ARRAY['Treadmill','Dumbbells','Bench Press','Cable Machine','Stationary Bike'], ARRAY['Changing Rooms','Showers','Lockers','Water Cooler'], 5, 240),
  ('550253', 'Studio', ARRAY[]::text[], ARRAY['Water Cooler'], null, null),
  ('550264', 'Badminton Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 3, null),
  ('550264', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('550264', 'Gymnasium', ARRAY['Treadmill','Dumbbells','Bench Press','Cable Machine','Stationary Bike'], ARRAY['Changing Rooms','Showers','Lockers','Water Cooler'], 4, 180),
  ('550264', 'Studio', ARRAY[]::text[], ARRAY['Water Cooler'], null, null),
  ('550266', 'Badminton Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 8, null),
  ('550267', 'Basketball Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 3, null),
  ('550307', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('550309', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('550314', 'Badminton Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 6, null),
  ('550319', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('550321', 'Badminton Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 3, null),
  ('550321', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('550321', 'Jogging Track', ARRAY[]::text[], ARRAY['Bleachers','Water Cooler','Toilets'], null, null),
  ('550328', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('550330', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('550335', 'Badminton Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 3, null),
  ('550335', 'Sepak Takraw Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 4, null),
  ('550335', 'Volleyball Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 5, null),
  ('550401', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('550402', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('550402', 'Jogging Track', ARRAY[]::text[], ARRAY['Bleachers','Water Cooler','Toilets'], null, null),
  ('550403', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('550410', 'Badminton Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 5, null),
  ('550410', 'Sepak Takraw Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 6, null),
  ('550410', 'Volleyball Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 8, null),
  ('550417', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('550419', 'Basketball Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 4, null),
  ('550419', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('550501', 'Table tennis Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 6, null),
  ('550504', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('550507', 'Table tennis Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 3, null),
  ('550510', 'Basketball Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 4, null),
  ('550510', 'Futsal / Street Soccer Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 5, null),
  ('550510', 'Table tennis Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 6, null),
  ('550511', 'Badminton Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 8, null),
  ('550511', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('550517', 'Badminton Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 4, null),
  ('550518', 'Badminton Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 5, null),
  ('550522', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('550524', 'Badminton Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 8, null),
  ('550533', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('550535', 'Badminton Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 4, null),
  ('550535', 'Basketball Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 5, null),
  ('550535', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('550535', 'Jogging Track', ARRAY[]::text[], ARRAY['Bleachers','Water Cooler','Toilets'], null, null),
  ('550537', 'Tennis Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 3, null),
  ('550538', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('550540', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('550542', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('550542', 'Jogging Track', ARRAY[]::text[], ARRAY['Bleachers','Water Cooler','Toilets'], null, null),
  ('550544', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('550546', 'Badminton Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 4, null),
  ('550546', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('550546', 'Sepak Takraw Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 6, null),
  ('550546', 'Volleyball Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 8, null),
  ('550547', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('550552', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('551234', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('551535', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('551542', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('554336', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('554336', 'Golf', ARRAY[]::text[], ARRAY['Water Cooler'], null, null),
  ('554336', 'Gymnasium', ARRAY['Treadmill','Dumbbells','Bench Press','Cable Machine','Stationary Bike'], ARRAY['Changing Rooms','Showers','Lockers','Water Cooler'], 4, 180),
  ('554336', 'Jogging Track', ARRAY[]::text[], ARRAY['Bleachers','Water Cooler','Toilets'], null, null),
  ('554336', 'Swimming Pool', ARRAY[]::text[], ARRAY['Changing Rooms','Showers','Lockers'], 2, null),
  ('554336', 'Tennis Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 3, null),
  ('554343', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('554343', 'Golf', ARRAY[]::text[], ARRAY['Water Cooler'], null, null),
  ('554343', 'Gymnasium', ARRAY['Treadmill','Dumbbells','Bench Press','Cable Machine','Stationary Bike'], ARRAY['Changing Rooms','Showers','Lockers','Water Cooler'], 5, 240),
  ('554343', 'Studio', ARRAY[]::text[], ARRAY['Water Cooler'], null, null),
  ('554343', 'Swimming Pool', ARRAY[]::text[], ARRAY['Changing Rooms','Showers','Lockers'], 1, null),
  ('554343', 'Tennis Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 4, null),
  ('554479', 'Basketball Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 5, null),
  ('554479', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('554479', 'Gymnasium', ARRAY['Treadmill','Dumbbells','Bench Press','Cable Machine','Stationary Bike'], ARRAY['Changing Rooms','Showers','Lockers','Water Cooler'], 6, 300),
  ('554479', 'Jogging Track', ARRAY[]::text[], ARRAY['Bleachers','Water Cooler','Toilets'], null, null),
  ('554479', 'Swimming Pool', ARRAY[]::text[], ARRAY['Changing Rooms','Showers','Lockers'], 2, null),
  ('554479', 'Tennis Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 5, null),
  ('554480', 'Gymnasium', ARRAY['Treadmill','Dumbbells','Bench Press','Cable Machine','Stationary Bike'], ARRAY['Changing Rooms','Showers','Lockers','Water Cooler'], 5, 240),
  ('554480', 'Swimming Pool', ARRAY[]::text[], ARRAY['Changing Rooms','Showers','Lockers'], 1.5, null),
  ('554574', 'Studio', ARRAY[]::text[], ARRAY['Water Cooler'], null, null),
  ('554628', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('554775', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('554775', 'Gymnasium', ARRAY['Treadmill','Dumbbells','Bench Press','Cable Machine','Stationary Bike'], ARRAY['Changing Rooms','Showers','Lockers','Water Cooler'], 5, 240),
  ('554775', 'Swimming Pool', ARRAY[]::text[], ARRAY['Changing Rooms','Showers','Lockers'], 2, null),
  ('554775', 'Tennis Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 3, null),
  ('555133', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('555133', 'Jogging Track', ARRAY[]::text[], ARRAY['Bleachers','Water Cooler','Toilets'], null, null),
  ('555257', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('555853', 'Cue Sports Table', ARRAY[]::text[], ARRAY['Water Cooler'], null, null),
  ('555853', 'Table Tennis Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 3, null),
  ('555855', 'Badminton Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 4, null),
  ('555855', 'Basketball Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 5, null),
  ('555855', 'Football Field', ARRAY[]::text[], ARRAY['Bleachers','Water Cooler','Toilets'], null, null),
  ('555857', 'Gymnasium', ARRAY['Treadmill','Dumbbells','Bench Press','Cable Machine','Stationary Bike'], ARRAY['Changing Rooms','Showers','Lockers','Water Cooler'], 6, 300),
  ('555857', 'Studio', ARRAY[]::text[], ARRAY['Water Cooler'], null, null),
  ('555877', 'Gymnasium', ARRAY['Treadmill','Dumbbells','Bench Press','Cable Machine','Stationary Bike'], ARRAY['Changing Rooms','Showers','Lockers','Water Cooler'], 3, 120),
  ('555877', 'Studio', ARRAY[]::text[], ARRAY['Water Cooler'], null, null),
  ('555889', 'Badminton Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 6, null),
  ('555889', 'Basketball Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 8, null),
  ('555889', 'Football Field', ARRAY[]::text[], ARRAY['Bleachers','Water Cooler','Toilets'], null, null),
  ('555889', 'Netball Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 4, null),
  ('555889', 'Studio', ARRAY[]::text[], ARRAY['Water Cooler'], null, null),
  ('555889', 'Table Tennis Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 6, null),
  ('555889', 'Volleyball Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 8, null),
  ('555949', 'Gymnasium', ARRAY['Treadmill','Dumbbells','Bench Press','Cable Machine','Stationary Bike'], ARRAY['Changing Rooms','Showers','Lockers','Water Cooler'], 2.5, 90),
  ('555950', 'Studio', ARRAY[]::text[], ARRAY['Water Cooler'], null, null),
  ('555965', 'Gymnasium', ARRAY['Treadmill','Dumbbells','Bench Press','Cable Machine','Stationary Bike'], ARRAY['Changing Rooms','Showers','Lockers','Water Cooler'], 4, 180),
  ('556083', 'Gymnasium', ARRAY['Treadmill','Dumbbells','Bench Press','Cable Machine','Stationary Bike'], ARRAY['Changing Rooms','Showers','Lockers','Water Cooler'], 5, 240),
  ('556094', 'Badminton Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 8, null),
  ('556094', 'Basketball Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 3, null),
  ('556094', 'Netball Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 4, null),
  ('556094', 'Studio', ARRAY[]::text[], ARRAY['Water Cooler'], null, null),
  ('556094', 'Volleyball Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 6, null),
  ('556094', 'Wall Climbing', ARRAY[]::text[], ARRAY['Water Cooler'], null, null),
  ('556095', 'Badminton Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 3, null),
  ('556095', 'Basketball Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 4, null),
  ('556095', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('556095', 'Gymnasium', ARRAY['Treadmill','Dumbbells','Bench Press','Cable Machine','Stationary Bike'], ARRAY['Changing Rooms','Showers','Lockers','Water Cooler'], 5, 240),
  ('556095', 'Studio', ARRAY[]::text[], ARRAY['Water Cooler'], null, null),
  ('556095', 'Volleyball Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 3, null),
  ('556108', 'Badminton Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 4, null),
  ('556108', 'Basketball Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 5, null),
  ('556108', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('556108', 'Gymnasium', ARRAY['Treadmill','Dumbbells','Bench Press','Cable Machine','Stationary Bike'], ARRAY['Changing Rooms','Showers','Lockers','Water Cooler'], 6, 300),
  ('556108', 'Jogging Track', ARRAY[]::text[], ARRAY['Bleachers','Water Cooler','Toilets'], null, null),
  ('556108', 'Netball Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 4, null),
  ('556108', 'Studio', ARRAY[]::text[], ARRAY['Water Cooler'], null, null),
  ('556108', 'Volleyball Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 6, null),
  ('556111', 'Football Field', ARRAY[]::text[], ARRAY['Bleachers','Water Cooler','Toilets'], null, null),
  ('556111', 'Studio', ARRAY[]::text[], ARRAY['Water Cooler'], null, null),
  ('556114', 'Squash Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 4, null),
  ('556114', 'Swimming Pool', ARRAY[]::text[], ARRAY['Changing Rooms','Showers','Lockers'], 2, null),
  ('556114', 'Tennis Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 6, null),
  ('556120', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('556120', 'Gymnasium', ARRAY['Treadmill','Dumbbells','Bench Press','Cable Machine','Stationary Bike'], ARRAY['Changing Rooms','Showers','Lockers','Water Cooler'], 2.5, 90),
  ('556120', 'Jogging track', ARRAY[]::text[], ARRAY['Bleachers','Water Cooler','Toilets'], null, null),
  ('556120', 'Squash Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 5, null),
  ('556120', 'Swimming Pool', ARRAY[]::text[], ARRAY['Changing Rooms','Showers','Lockers'], 1, null),
  ('556120', 'Tennis Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 8, null),
  ('556123', 'Badminton Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 3, null),
  ('556123', 'Basketball Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 4, null),
  ('556123', 'Football Field', ARRAY[]::text[], ARRAY['Bleachers','Water Cooler','Toilets'], null, null),
  ('556123', 'Gymnasium', ARRAY['Treadmill','Dumbbells','Bench Press','Cable Machine','Stationary Bike'], ARRAY['Changing Rooms','Showers','Lockers','Water Cooler'], 5, 240),
  ('556123', 'Shooting Range', ARRAY[]::text[], ARRAY['Water Cooler'], null, null),
  ('556123', 'Table Tennis Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 3, null),
  ('556123', 'Volleyball Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 4, null),
  ('556124', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('556124', 'Gymnasium', ARRAY['Treadmill','Dumbbells','Bench Press','Cable Machine','Stationary Bike'], ARRAY['Changing Rooms','Showers','Lockers','Water Cooler'], 5, 240),
  ('556124', 'Jogging track', ARRAY[]::text[], ARRAY['Bleachers','Water Cooler','Toilets'], null, null),
  ('556124', 'Swimming Pool', ARRAY[]::text[], ARRAY['Changing Rooms','Showers','Lockers'], 1, null),
  ('556124', 'Tennis Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 4, null),
  ('556126', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('556126', 'Swimming Pool', ARRAY[]::text[], ARRAY['Changing Rooms','Showers','Lockers'], 2.5, null),
  ('556136', 'Gymnasium', ARRAY['Treadmill','Dumbbells','Bench Press','Cable Machine','Stationary Bike'], ARRAY['Changing Rooms','Showers','Lockers','Water Cooler'], 6, 300),
  ('556136', 'Jogging track', ARRAY[]::text[], ARRAY['Bleachers','Water Cooler','Toilets'], null, null),
  ('556136', 'Swimming Pool', ARRAY[]::text[], ARRAY['Changing Rooms','Showers','Lockers'], 2, null),
  ('556136', 'Tennis Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 5, null),
  ('556140', 'Badminton Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 6, null),
  ('556140', 'Basketball Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 8, null),
  ('556140', 'Football Field', ARRAY[]::text[], ARRAY['Bleachers','Water Cooler','Toilets'], null, null),
  ('556140', 'Shooting Range', ARRAY[]::text[], ARRAY['Water Cooler'], null, null),
  ('556140', 'Table Tennis Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 5, null),
  ('556624', 'Gymnasium', ARRAY['Treadmill','Dumbbells','Bench Press','Cable Machine','Stationary Bike'], ARRAY['Changing Rooms','Showers','Lockers','Water Cooler'], 5, 240),
  ('556624', 'Swimming Pool', ARRAY[]::text[], ARRAY['Changing Rooms','Showers','Lockers'], 2, null),
  ('556741', 'Gymnasium', ARRAY['Treadmill','Dumbbells','Bench Press','Cable Machine','Stationary Bike'], ARRAY['Changing Rooms','Showers','Lockers','Water Cooler'], 2.5, 90),
  ('556741', 'Studio', ARRAY[]::text[], ARRAY['Water Cooler'], null, null),
  ('556742', 'Badminton Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 5, null),
  ('556742', 'Basketball Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 6, null),
  ('556742', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('556742', 'Football Field', ARRAY[]::text[], ARRAY['Bleachers','Water Cooler','Toilets'], null, null),
  ('556742', 'Futsal / Street Soccer Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 4, null),
  ('556742', 'Gymnasium', ARRAY['Treadmill','Dumbbells','Bench Press','Cable Machine','Stationary Bike'], ARRAY['Changing Rooms','Showers','Lockers','Water Cooler'], 4, 180),
  ('556742', 'Studio', ARRAY[]::text[], ARRAY['Water Cooler'], null, null),
  ('556743', 'Gymnasium', ARRAY['Treadmill','Dumbbells','Bench Press','Cable Machine','Stationary Bike'], ARRAY['Changing Rooms','Showers','Lockers','Water Cooler'], 6, 300),
  ('556743', 'Squash Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 3, null),
  ('556743', 'Swimming Pool', ARRAY[]::text[], ARRAY['Changing Rooms','Showers','Lockers'], 2, null),
  ('556743', 'Table Tennis Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 5, null),
  ('556743', 'Tennis Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 6, null),
  ('556818', 'Badminton Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 8, null),
  ('556818', 'Basketball Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 3, null),
  ('556818', 'Football Field', ARRAY[]::text[], ARRAY['Bleachers','Water Cooler','Toilets'], null, null),
  ('556818', 'Gymnasium', ARRAY['Treadmill','Dumbbells','Bench Press','Cable Machine','Stationary Bike'], ARRAY['Changing Rooms','Showers','Lockers','Water Cooler'], 4, 180),
  ('556818', 'Netball Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 6, null),
  ('556818', 'Rugby Field', ARRAY[]::text[], ARRAY['Bleachers','Water Cooler','Toilets'], null, null),
  ('556818', 'Swimming Pool', ARRAY[]::text[], ARRAY['Changing Rooms','Showers','Lockers'], 2.5, null),
  ('556818', 'Table Tennis Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 4, null),
  ('556818', 'Volleyball Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 5, null),
  ('556820', 'Basketball Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 6, null),
  ('556820', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('556820', 'Gymnasium', ARRAY['Treadmill','Dumbbells','Bench Press','Cable Machine','Stationary Bike'], ARRAY['Changing Rooms','Showers','Lockers','Water Cooler'], 2.5, 90),
  ('556820', 'Swimming Pool', ARRAY[]::text[], ARRAY['Changing Rooms','Showers','Lockers'], 1.5, null),
  ('556820', 'Tennis Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 5, null),
  ('557271', 'Bowling Alley', ARRAY[]::text[], ARRAY['Water Cooler'], null, null),
  ('557271', 'Cue Sports Table', ARRAY[]::text[], ARRAY['Water Cooler'], null, null),
  ('557271', 'Gymnasium', ARRAY['Treadmill','Dumbbells','Bench Press','Cable Machine','Stationary Bike'], ARRAY['Changing Rooms','Showers','Lockers','Water Cooler'], 2.5, 90),
  ('557271', 'Squash Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 4, null),
  ('557271', 'Swimming Pool', ARRAY[]::text[], ARRAY['Changing Rooms','Showers','Lockers'], 2.5, null),
  ('557271', 'Table tennis Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 6, null),
  ('557271', 'Tennis Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 8, null),
  ('557323', 'Basketball Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 3, null),
  ('557323', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('557323', 'Football Field', ARRAY[]::text[], ARRAY['Bleachers','Water Cooler','Toilets'], null, null),
  ('557323', 'Gymnasium', ARRAY['Treadmill','Dumbbells','Bench Press','Cable Machine','Stationary Bike'], ARRAY['Changing Rooms','Showers','Lockers','Water Cooler'], 5, 240),
  ('557323', 'Swimming Pool', ARRAY[]::text[], ARRAY['Changing Rooms','Showers','Lockers'], 2, null),
  ('557323', 'Table Tennis Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 3, null),
  ('557425', 'Swimming Pool', ARRAY[]::text[], ARRAY['Changing Rooms','Showers','Lockers'], 1, null),
  ('558438', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('558570', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('558691', 'Swimming Pool', ARRAY[]::text[], ARRAY['Changing Rooms','Showers','Lockers'], 2.5, null),
  ('558961', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('558961', 'Gymnasium', ARRAY['Treadmill','Dumbbells','Bench Press','Cable Machine','Stationary Bike'], ARRAY['Changing Rooms','Showers','Lockers','Water Cooler'], 3, 120),
  ('558961', 'Swimming Pool', ARRAY[]::text[], ARRAY['Changing Rooms','Showers','Lockers'], 2, null),
  ('558979', 'Gymnasium', ARRAY['Treadmill','Dumbbells','Bench Press','Cable Machine','Stationary Bike'], ARRAY['Changing Rooms','Showers','Lockers','Water Cooler'], 5, 240),
  ('558979', 'Netball Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 8, null),
  ('558979', 'Studio', ARRAY[]::text[], ARRAY['Water Cooler'], null, null),
  ('559020', 'Squash Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 4, null),
  ('559020', 'Tennis Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 5, null),
  ('559258', 'Swimming Pool', ARRAY[]::text[], ARRAY['Changing Rooms','Showers','Lockers'], 1, null),
  ('559697', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('559697', 'Jogging Track', ARRAY[]::text[], ARRAY['Bleachers','Water Cooler','Toilets'], null, null),
  ('560101', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('560104', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('560106', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('560110', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('560112', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('560124', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('560129', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('560134', 'Basketball Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 6, null),
  ('560134', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('560156', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('560171', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('560173', 'Basketball Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 5, null),
  ('560173', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('560177', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('560179', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('560180', 'Basketball Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 4, null),
  ('560203', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('560209', 'Badminton Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 6, null),
  ('560209', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('560209', 'Sepak Takraw Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 3, null),
  ('560209', 'Volleyball Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 4, null),
  ('560212', 'Table Tennis Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 5, null),
  ('560213', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('560225', 'Table Tennis Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 8, null),
  ('560244', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('560254', 'Badminton Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 4, null),
  ('560254', 'Sepak Takraw Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 5, null),
  ('560254', 'Volleyball Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 6, null),
  ('560258', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('560259', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('560329', 'Futsal / Street Soccer Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 4, null),
  ('560340', 'Gymnasium', ARRAY['Treadmill','Dumbbells','Bench Press','Cable Machine','Stationary Bike'], ARRAY['Changing Rooms','Showers','Lockers','Water Cooler'], 4, 180),
  ('560340', 'Studio', ARRAY[]::text[], ARRAY['Water Cooler'], null, null),
  ('560350', 'Basketball Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 8, null),
  ('560413', 'Futsal / Street Soccer Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 3, null),
  ('560423', 'Badminton Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 4, null),
  ('560423', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('560426', 'Table Tennis Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 6, null),
  ('560427', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('560428', 'Badminton Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 3, null),
  ('560429', 'Badminton Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 4, null),
  ('560429', 'Table tennis Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 5, null),
  ('560433', 'Table tennis Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 6, null),
  ('560435', 'Badminton Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 8, null),
  ('560435', 'Table tennis Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 3, null),
  ('560436', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('560437', 'Basketball Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 5, null),
  ('560437', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('560437', 'Futsal / Street Soccer Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 8, null),
  ('560438', 'Table tennis Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 3, null),
  ('560440', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('560441', 'Table tennis Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 5, null),
  ('560441', 'Table Tennis Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 6, null),
  ('560442', 'Table Tennis Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 8, null),
  ('560443', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('560459', 'Basketball Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 4, null),
  ('560462', 'Basketball Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 5, null),
  ('560501', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('560511', 'Badminton Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 8, null),
  ('560511', 'Basketball Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 3, null),
  ('560511', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('560513', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('560523', 'Badminton Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 6, null),
  ('560524', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('560536', 'Basketball Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 3, null),
  ('560537', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('560538', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('560540', 'Badminton Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 6, null),
  ('560540', 'Futsal / Street Soccer Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 8, null),
  ('560543', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('560544', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('560546', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('560549', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('560551', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('560552', 'Badminton Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 3, null),
  ('560552', 'Basketball Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 4, null),
  ('560552', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('560556', 'Badminton Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 6, null),
  ('560562', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('560564', 'Basketball Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 3, null),
  ('560564', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('560564', 'Futsal / Street Soccer Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 5, null),
  ('560570', 'Badminton Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 6, null),
  ('560570', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('560570', 'Sepak Takraw Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 3, null),
  ('560571', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('560585', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('560588', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('560602', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('560603', 'Basketball Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 3, null),
  ('560606', 'Jogging Track', ARRAY[]::text[], ARRAY['Bleachers','Water Cooler','Toilets'], null, null),
  ('560607', 'Badminton Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 5, null),
  ('560607', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('560608', 'Badminton Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 8, null),
  ('560610', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('560611', 'Jogging Track', ARRAY[]::text[], ARRAY['Bleachers','Water Cooler','Toilets'], null, null),
  ('560618', 'Badminton Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 5, null),
  ('560618', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('560622', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('560624', 'Table tennis Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 3, null),
  ('560627', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('560632', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('560635', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('560638', 'Basketball Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 8, null),
  ('560638', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('560642', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('560646', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('560648', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('560650', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null)
on conflict (postal_code, facility_type) do update
set
  equipment = excluded.equipment,
  amenities = excluded.amenities,
  day_pass_price = excluded.day_pass_price,
  membership_price = excluded.membership_price;
