insert into public.gym_enrichments (
  postal_code,
  facility_type,
  equipment,
  amenities,
  day_pass_price,
  membership_price
)
values
  ('598740', 'Swimming Pool', ARRAY[]::text[], ARRAY['Changing Rooms','Showers','Lockers'], 1, null),
  ('598740', 'Tennis Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 4, null),
  ('598746', 'Gymnasium', ARRAY['Treadmill','Dumbbells','Bench Press','Cable Machine','Stationary Bike'], ARRAY['Changing Rooms','Showers','Lockers','Water Cooler'], 4, 180),
  ('598746', 'Swimming Pool', ARRAY[]::text[], ARRAY['Changing Rooms','Showers','Lockers'], 2.5, null),
  ('598746', 'Tennis Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 8, null),
  ('598750', 'Gymnasium', ARRAY['Treadmill','Dumbbells','Bench Press','Cable Machine','Stationary Bike'], ARRAY['Changing Rooms','Showers','Lockers','Water Cooler'], 2.5, 90),
  ('598750', 'Swimming Pool', ARRAY[]::text[], ARRAY['Changing Rooms','Showers','Lockers'], 2, null),
  ('598750', 'Tennis Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 5, null),
  ('598756', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('598890', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('599174', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('599302', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('599426', 'Swimming Pool', ARRAY[]::text[], ARRAY['Changing Rooms','Showers','Lockers'], 1, null),
  ('599458', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('599458', 'Gymnasium', ARRAY['Treadmill','Dumbbells','Bench Press','Cable Machine','Stationary Bike'], ARRAY['Changing Rooms','Showers','Lockers','Water Cooler'], 6, 300),
  ('599458', 'Studio', ARRAY[]::text[], ARRAY['Water Cooler'], null, null),
  ('599458', 'Swimming Pool', ARRAY[]::text[], ARRAY['Changing Rooms','Showers','Lockers'], 1, null),
  ('599489', 'Athletics Track', ARRAY[]::text[], ARRAY['Bleachers','Water Cooler','Toilets'], null, null),
  ('599489', 'Badminton Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 6, null),
  ('599489', 'Basketball Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 8, null),
  ('599489', 'Floorball Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 3, null),
  ('599489', 'Football Field', ARRAY[]::text[], ARRAY['Bleachers','Water Cooler','Toilets'], null, null),
  ('599489', 'Futsal / Street Soccer Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 5, null),
  ('599489', 'Gymnasium', ARRAY['Treadmill','Dumbbells','Bench Press','Cable Machine','Stationary Bike'], ARRAY['Changing Rooms','Showers','Lockers','Water Cooler'], 5, 240),
  ('599489', 'Netball Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 8, null),
  ('599489', 'Rugby Field', ARRAY[]::text[], ARRAY['Bleachers','Water Cooler','Toilets'], null, null),
  ('599489', 'Softball / Baseball Field', ARRAY[]::text[], ARRAY['Bleachers','Water Cooler','Toilets'], null, null),
  ('599489', 'Squash Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 5, null),
  ('599489', 'Studio', ARRAY[]::text[], ARRAY['Water Cooler'], null, null),
  ('599489', 'Swimming Pool', ARRAY[]::text[], ARRAY['Changing Rooms','Showers','Lockers'], 1.5, null),
  ('599489', 'Table tennis Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 3, null),
  ('599489', 'Tennis Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 4, null),
  ('599489', 'Volleyball Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 5, null),
  ('599491', 'Basketball Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 6, null),
  ('599491', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('599491', 'Football Field', ARRAY[]::text[], ARRAY['Bleachers','Water Cooler','Toilets'], null, null),
  ('599491', 'Futsal / Street Soccer Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 4, null),
  ('599491', 'Gymnasium', ARRAY['Treadmill','Dumbbells','Bench Press','Cable Machine','Stationary Bike'], ARRAY['Changing Rooms','Showers','Lockers','Water Cooler'], 4, 180),
  ('599491', 'Netball Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 6, null),
  ('599491', 'Rugby Field', ARRAY[]::text[], ARRAY['Bleachers','Water Cooler','Toilets'], null, null),
  ('599491', 'Volleyball Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 3, null),
  ('599568', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('599717', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('599717', 'Golf', ARRAY[]::text[], ARRAY['Water Cooler'], null, null),
  ('599717', 'Gymnasium', ARRAY['Treadmill','Dumbbells','Bench Press','Cable Machine','Stationary Bike'], ARRAY['Changing Rooms','Showers','Lockers','Water Cooler'], 6, 300),
  ('599717', 'Swimming Pool', ARRAY[]::text[], ARRAY['Changing Rooms','Showers','Lockers'], 1.5, null),
  ('599804', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('599973', 'Gymnasium', ARRAY['Treadmill','Dumbbells','Bench Press','Cable Machine','Stationary Bike'], ARRAY['Changing Rooms','Showers','Lockers','Water Cooler'], 4, 180),
  ('599973', 'Squash Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 6, null),
  ('599973', 'Swimming Pool', ARRAY[]::text[], ARRAY['Changing Rooms','Showers','Lockers'], 1.5, null),
  ('599973', 'Tennis Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 3, null),
  ('599986', 'Badminton Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 4, null),
  ('599986', 'Basketball Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 5, null),
  ('599986', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('599986', 'Football Field', ARRAY[]::text[], ARRAY['Bleachers','Water Cooler','Toilets'], null, null),
  ('599986', 'Gymnasium', ARRAY['Treadmill','Dumbbells','Bench Press','Cable Machine','Stationary Bike'], ARRAY['Changing Rooms','Showers','Lockers','Water Cooler'], 2.5, 90),
  ('599986', 'Netball Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 4, null),
  ('599986', 'Squash Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 5, null),
  ('599986', 'Studio', ARRAY[]::text[], ARRAY['Water Cooler'], null, null),
  ('599986', 'Swimming Pool', ARRAY[]::text[], ARRAY['Changing Rooms','Showers','Lockers'], 2.5, null),
  ('599986', 'Table Tennis Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 3, null),
  ('599986', 'Tennis Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 4, null),
  ('599986', 'Volleyball Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 5, null),
  ('600021', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('600041', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('600041', 'Futsal / Street Soccer Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 3, null),
  ('600044', 'Basketball Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 4, null),
  ('600047', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('600048', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('600050', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('600051', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('600052', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('600053', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('600055', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('600063', 'Badminton Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 8, null),
  ('600063', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('600063', 'Futsal / Street Soccer Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 4, null),
  ('600101', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('600107', 'Basketball Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 6, null),
  ('600107', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('600107', 'Futsal / Street Soccer Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 3, null),
  ('600108', 'Squash Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 4, null),
  ('600109', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('600111', 'Badminton Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 6, null),
  ('600114', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('600117', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('600130', 'Gymnasium', ARRAY['Treadmill','Dumbbells','Bench Press','Cable Machine','Stationary Bike'], ARRAY['Changing Rooms','Showers','Lockers','Water Cooler'], 3, 120),
  ('600134', 'Gymnasium', ARRAY['Treadmill','Dumbbells','Bench Press','Cable Machine','Stationary Bike'], ARRAY['Changing Rooms','Showers','Lockers','Water Cooler'], 4, 180),
  ('600134', 'Studio', ARRAY[]::text[], ARRAY['Water Cooler'], null, null),
  ('600135', 'Gymnasium', ARRAY['Treadmill','Dumbbells','Bench Press','Cable Machine','Stationary Bike'], ARRAY['Changing Rooms','Showers','Lockers','Water Cooler'], 6, 300),
  ('600135', 'Studio', ARRAY[]::text[], ARRAY['Water Cooler'], null, null),
  ('600203', 'Badminton Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 4, null),
  ('600205', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('600208', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('600209', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('600211', 'Futsal / Street Soccer Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 3, null),
  ('600212', 'Badminton Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 4, null),
  ('600214', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('600224', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('600226', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('600236', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('600238', 'Basketball Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 4, null),
  ('600242', 'Basketball Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 5, null),
  ('600242', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('600252', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('600255', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('600262', 'Basketball Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 4, null),
  ('600266', 'Badminton Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 5, null),
  ('600269', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('600280', 'Badminton Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 8, null),
  ('600282', 'Badminton Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 3, null),
  ('600303', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('600305', 'Basketball Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 5, null),
  ('600305', 'Futsal / Street Soccer Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 6, null),
  ('600306', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('600308', 'Basketball Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 3, null),
  ('600308', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('600309', 'Badminton Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 5, null),
  ('600311', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('600312', 'Tennis Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 8, null),
  ('600315', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('600316', 'Badminton Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 4, null),
  ('600324', 'Basketball Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 5, null),
  ('600327', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('600331', 'Badminton Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 8, null),
  ('600340', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('600401', 'Cycling Track', ARRAY[]::text[], ARRAY['Bleachers','Water Cooler','Toilets'], null, null),
  ('600401', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('600401', 'Jogging Track', ARRAY[]::text[], ARRAY['Bleachers','Water Cooler','Toilets'], null, null),
  ('600404', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('600406', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('600407', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('600410', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('600410', 'Futsal / Street Soccer Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 6, null),
  ('600413', 'Golf', ARRAY[]::text[], ARRAY['Water Cooler'], null, null),
  ('601021', 'Badminton Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 3, null),
  ('601021', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('601022', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('601219', 'Basketball Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 6, null),
  ('601221', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('601288', 'Badminton Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 3, null),
  ('601288', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('602286', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('602318', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('603286', 'Badminton Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 8, null),
  ('603287', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('608512', 'Padel Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 4, null),
  ('608512', 'Swimming Pool', ARRAY[]::text[], ARRAY['Changing Rooms','Showers','Lockers'], 2.5, null),
  ('608532', 'Gymnasium', ARRAY['Treadmill','Dumbbells','Bench Press','Cable Machine','Stationary Bike'], ARRAY['Changing Rooms','Showers','Lockers','Water Cooler'], 5, 240),
  ('608532', 'Studio', ARRAY[]::text[], ARRAY['Water Cooler'], null, null),
  ('608533', 'Swimming Pool', ARRAY[]::text[], ARRAY['Changing Rooms','Showers','Lockers'], 2, null),
  ('608550', 'Gymnasium', ARRAY['Treadmill','Dumbbells','Bench Press','Cable Machine','Stationary Bike'], ARRAY['Changing Rooms','Showers','Lockers','Water Cooler'], 3, 120),
  ('608784', 'Badminton Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 5, null),
  ('608784', 'Basketball Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 6, null),
  ('608784', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('608784', 'Football Field', ARRAY[]::text[], ARRAY['Bleachers','Water Cooler','Toilets'], null, null),
  ('608784', 'Netball Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 4, null),
  ('608784', 'Studio', ARRAY[]::text[], ARRAY['Water Cooler'], null, null),
  ('608784', 'Volleyball Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 6, null),
  ('608836', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('608839', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('609078', 'Cue Sports Table', ARRAY[]::text[], ARRAY['Water Cooler'], null, null),
  ('609078', 'Golf', ARRAY[]::text[], ARRAY['Water Cooler'], null, null),
  ('609078', 'Gymnasium', ARRAY['Treadmill','Dumbbells','Bench Press','Cable Machine','Stationary Bike'], ARRAY['Changing Rooms','Showers','Lockers','Water Cooler'], 5, 240),
  ('609078', 'Squash Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 8, null),
  ('609078', 'Studio', ARRAY[]::text[], ARRAY['Water Cooler'], null, null),
  ('609078', 'Swimming Pool', ARRAY[]::text[], ARRAY['Changing Rooms','Showers','Lockers'], 2, null),
  ('609078', 'Table Tennis Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 5, null),
  ('609078', 'Tennis Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 6, null),
  ('609079', 'Badminton Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 8, null),
  ('609079', 'Basketball Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 3, null),
  ('609079', 'Football Field', ARRAY[]::text[], ARRAY['Bleachers','Water Cooler','Toilets'], null, null),
  ('609079', 'Netball Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 5, null),
  ('609079', 'Table Tennis Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 6, null),
  ('609079', 'Tennis Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 8, null),
  ('609273', 'Gymnasium', ARRAY['Treadmill','Dumbbells','Bench Press','Cable Machine','Stationary Bike'], ARRAY['Changing Rooms','Showers','Lockers','Water Cooler'], 2.5, 90),
  ('609336', 'Softball / Baseball Field', ARRAY[]::text[], ARRAY['Bleachers','Water Cooler','Toilets'], null, null),
  ('609342', 'Badminton Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 5, null),
  ('609433', 'Climbing Wall', ARRAY[]::text[], ARRAY['Water Cooler'], null, null),
  ('609433', 'Ski Slope', ARRAY[]::text[], ARRAY['Water Cooler'], null, null),
  ('609434', 'Badminton Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 3, null),
  ('609434', 'Basketball Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 4, null),
  ('609434', 'Cue Sports Table', ARRAY[]::text[], ARRAY['Water Cooler'], null, null),
  ('609434', 'Gymnasium', ARRAY['Treadmill','Dumbbells','Bench Press','Cable Machine','Stationary Bike'], ARRAY['Changing Rooms','Showers','Lockers','Water Cooler'], 5, 240),
  ('609434', 'Squash Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 8, null),
  ('609434', 'Studio', ARRAY[]::text[], ARRAY['Water Cooler'], null, null),
  ('609434', 'Table Tennis Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 4, null),
  ('609434', 'Tennis Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 5, null),
  ('609476', 'Badminton Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 6, null),
  ('609476', 'Basketball Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 8, null),
  ('609476', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('609476', 'Gymnasium', ARRAY['Treadmill','Dumbbells','Bench Press','Cable Machine','Stationary Bike'], ARRAY['Changing Rooms','Showers','Lockers','Water Cooler'], 3, 120),
  ('609476', 'Netball Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 5, null),
  ('609476', 'Studio', ARRAY[]::text[], ARRAY['Water Cooler'], null, null),
  ('609476', 'Table Tennis Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 8, null),
  ('609476', 'Volleyball Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 3, null),
  ('609478', 'Bowling Alley', ARRAY[]::text[], ARRAY['Water Cooler'], null, null),
  ('609478', 'Gymnasium', ARRAY['Treadmill','Dumbbells','Bench Press','Cable Machine','Stationary Bike'], ARRAY['Changing Rooms','Showers','Lockers','Water Cooler'], 4, 180),
  ('609478', 'Swimming Pool', ARRAY[]::text[], ARRAY['Changing Rooms','Showers','Lockers'], 2, null),
  ('609478', 'Tennis Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 8, null),
  ('609517', 'Badminton Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 3, null),
  ('609517', 'Football Field', ARRAY[]::text[], ARRAY['Bleachers','Water Cooler','Toilets'], null, null),
  ('609517', 'Futsal / Street Soccer Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 5, null),
  ('609517', 'Gateball Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 6, null),
  ('609517', 'Gymnasium', ARRAY['Treadmill','Dumbbells','Bench Press','Cable Machine','Stationary Bike'], ARRAY['Changing Rooms','Showers','Lockers','Water Cooler'], 6, 300),
  ('609517', 'Jogging Track', ARRAY[]::text[], ARRAY['Bleachers','Water Cooler','Toilets'], null, null),
  ('609517', 'Petanque Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 4, null),
  ('609517', 'Pickleball Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 5, null),
  ('609517', 'Studio', ARRAY[]::text[], ARRAY['Water Cooler'], null, null),
  ('609517', 'Swimming Pool', ARRAY[]::text[], ARRAY['Changing Rooms','Showers','Lockers'], 1.5, null),
  ('609517', 'Table tennis Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 3, null),
  ('609558', 'Badminton Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 4, null),
  ('609558', 'Basketball Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 5, null),
  ('609558', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('609558', 'Football Field', ARRAY[]::text[], ARRAY['Bleachers','Water Cooler','Toilets'], null, null),
  ('609558', 'Netball Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 3, null),
  ('609558', 'Studio', ARRAY[]::text[], ARRAY['Water Cooler'], null, null),
  ('609558', 'Volleyball Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 5, null),
  ('609561', 'Badminton Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 6, null),
  ('609561', 'Basketball Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 8, null),
  ('609561', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('609561', 'Football Field', ARRAY[]::text[], ARRAY['Bleachers','Water Cooler','Toilets'], null, null),
  ('609561', 'Gymnasium', ARRAY['Treadmill','Dumbbells','Bench Press','Cable Machine','Stationary Bike'], ARRAY['Changing Rooms','Showers','Lockers','Water Cooler'], 4, 180),
  ('609561', 'Netball Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 6, null),
  ('609561', 'Sepak Takraw Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 8, null),
  ('609561', 'Studio', ARRAY[]::text[], ARRAY['Water Cooler'], null, null),
  ('609561', 'Volleyball Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 4, null),
  ('609602', 'Table Tennis Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 5, null),
  ('609604', 'Badminton Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 6, null),
  ('609604', 'Basketball Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 8, null),
  ('609604', 'Football Field', ARRAY[]::text[], ARRAY['Bleachers','Water Cooler','Toilets'], null, null),
  ('609604', 'Gymnasium', ARRAY['Treadmill','Dumbbells','Bench Press','Cable Machine','Stationary Bike'], ARRAY['Changing Rooms','Showers','Lockers','Water Cooler'], 3, 120),
  ('609604', 'Volleyball Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 5, null),
  ('609647', 'Badminton Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 6, null),
  ('609647', 'Basketball Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 8, null),
  ('609647', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('609647', 'Football Field', ARRAY[]::text[], ARRAY['Bleachers','Water Cooler','Toilets'], null, null),
  ('609647', 'Gymnasium', ARRAY['Treadmill','Dumbbells','Bench Press','Cable Machine','Stationary Bike'], ARRAY['Changing Rooms','Showers','Lockers','Water Cooler'], 4, 180),
  ('609647', 'Netball Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 6, null),
  ('609647', 'Studio', ARRAY[]::text[], ARRAY['Water Cooler'], null, null),
  ('609647', 'Volleyball Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 3, null),
  ('609652', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('609652', 'Golf', ARRAY[]::text[], ARRAY['Water Cooler'], null, null),
  ('609652', 'Gymnasium', ARRAY['Treadmill','Dumbbells','Bench Press','Cable Machine','Stationary Bike'], ARRAY['Changing Rooms','Showers','Lockers','Water Cooler'], 5, 240),
  ('609652', 'Jogging track', ARRAY[]::text[], ARRAY['Bleachers','Water Cooler','Toilets'], null, null),
  ('609652', 'Swimming Pool', ARRAY[]::text[], ARRAY['Changing Rooms','Showers','Lockers'], 1.5, null),
  ('609652', 'Tennis Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 4, null),
  ('609731', 'Gymnasium', ARRAY['Treadmill','Dumbbells','Bench Press','Cable Machine','Stationary Bike'], ARRAY['Changing Rooms','Showers','Lockers','Water Cooler'], 4, 180),
  ('609731', 'Ice Skating Rink', ARRAY[]::text[], ARRAY['Water Cooler'], null, null),
  ('609731', 'Swimming Pool', ARRAY[]::text[], ARRAY['Changing Rooms','Showers','Lockers'], 1.5, null),
  ('609774', 'Golf', ARRAY[]::text[], ARRAY['Water Cooler'], null, null),
  ('609774', 'Gymnasium', ARRAY['Treadmill','Dumbbells','Bench Press','Cable Machine','Stationary Bike'], ARRAY['Changing Rooms','Showers','Lockers','Water Cooler'], 3, 120),
  ('609774', 'Jogging track', ARRAY[]::text[], ARRAY['Bleachers','Water Cooler','Toilets'], null, null),
  ('609774', 'Squash Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 6, null),
  ('609774', 'Swimming Pool', ARRAY[]::text[], ARRAY['Changing Rooms','Showers','Lockers'], 2, null),
  ('609774', 'Table Tennis Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 3, null),
  ('609774', 'Tennis Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 4, null),
  ('609789', 'Gymnasium', ARRAY['Treadmill','Dumbbells','Bench Press','Cable Machine','Stationary Bike'], ARRAY['Changing Rooms','Showers','Lockers','Water Cooler'], 4, 180),
  ('609790', 'Badminton Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 6, null),
  ('609790', 'Studio', ARRAY[]::text[], ARRAY['Water Cooler'], null, null),
  ('609832', 'Water Sports', ARRAY[]::text[], ARRAY['Water Cooler'], null, null),
  ('609914', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('609922', 'Gymnasium', ARRAY['Treadmill','Dumbbells','Bench Press','Cable Machine','Stationary Bike'], ARRAY['Changing Rooms','Showers','Lockers','Water Cooler'], 4, 180),
  ('609928', 'Gymnasium', ARRAY['Treadmill','Dumbbells','Bench Press','Cable Machine','Stationary Bike'], ARRAY['Changing Rooms','Showers','Lockers','Water Cooler'], 5, 240),
  ('609930', 'Gymnasium', ARRAY['Treadmill','Dumbbells','Bench Press','Cable Machine','Stationary Bike'], ARRAY['Changing Rooms','Showers','Lockers','Water Cooler'], 6, 300),
  ('609958', 'Badminton Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 3, null),
  ('609961', 'Bowling Alley', ARRAY[]::text[], ARRAY['Water Cooler'], null, null),
  ('609961', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('609961', 'Jogging Track', ARRAY[]::text[], ARRAY['Bleachers','Water Cooler','Toilets'], null, null),
  ('609963', 'Cycling Track', ARRAY[]::text[], ARRAY['Bleachers','Water Cooler','Toilets'], null, null),
  ('609963', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('609963', 'Jogging Track', ARRAY[]::text[], ARRAY['Bleachers','Water Cooler','Toilets'], null, null),
  ('610063', 'Badminton Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 5, null),
  ('610115', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('610116', 'Basketball Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 8, null),
  ('610120', 'Badminton Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 3, null),
  ('610120', 'Basketball Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 4, null),
  ('610120', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('610121', 'Futsal / Street Soccer Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 6, null),
  ('610122', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('610153', 'Badminton Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 3, null),
  ('610153', 'Basketball Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 4, null),
  ('610153', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('610154', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('610158', 'Badminton Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 8, null),
  ('610177', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('610179', 'Badminton Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 4, null),
  ('610325', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('610329', 'Basketball Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 6, null),
  ('610332', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('610349', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('610350', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('610365', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('610368', 'Badminton Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 6, null),
  ('610368', 'Basketball Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 8, null),
  ('610368', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('612337', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('612339', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('613337', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('614138', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('618310', 'Badminton Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 3, null),
  ('618310', 'Basketball Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 4, null),
  ('618310', 'Football Field', ARRAY[]::text[], ARRAY['Bleachers','Water Cooler','Toilets'], null, null),
  ('618310', 'Studio', ARRAY[]::text[], ARRAY['Water Cooler'], null, null),
  ('618310', 'Volleyball Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 8, null),
  ('618381', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('618495', 'Badminton Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 4, null),
  ('618495', 'Gymnasium', ARRAY['Treadmill','Dumbbells','Bench Press','Cable Machine','Stationary Bike'], ARRAY['Changing Rooms','Showers','Lockers','Water Cooler'], 4, 180),
  ('618495', 'Studio', ARRAY[]::text[], ARRAY['Water Cooler'], null, null),
  ('618640', 'Bowling Alley', ARRAY[]::text[], ARRAY['Water Cooler'], null, null),
  ('618652', 'Badminton Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 3, null),
  ('618652', 'Basketball Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 4, null),
  ('618652', 'Volleyball Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 5, null),
  ('618654', 'Badminton Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 6, null),
  ('618654', 'Basketball Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 8, null),
  ('618654', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('618654', 'Football Field', ARRAY[]::text[], ARRAY['Bleachers','Water Cooler','Toilets'], null, null),
  ('618654', 'Gymnasium', ARRAY['Treadmill','Dumbbells','Bench Press','Cable Machine','Stationary Bike'], ARRAY['Changing Rooms','Showers','Lockers','Water Cooler'], 4, 180),
  ('618654', 'Netball Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 6, null),
  ('618654', 'Studio', ARRAY[]::text[], ARRAY['Water Cooler'], null, null),
  ('618654', 'Table Tennis Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 3, null),
  ('618654', 'Volleyball Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 4, null),
  ('618664', 'Gymnasium', ARRAY['Treadmill','Dumbbells','Bench Press','Cable Machine','Stationary Bike'], ARRAY['Changing Rooms','Showers','Lockers','Water Cooler'], 4, 180),
  ('618664', 'Swimming Pool', ARRAY[]::text[], ARRAY['Changing Rooms','Showers','Lockers'], 2.5, null),
  ('618664', 'Table tennis Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 8, null),
  ('618721', 'Basketball Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 3, null),
  ('618721', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('618721', 'Gymnasium', ARRAY['Treadmill','Dumbbells','Bench Press','Cable Machine','Stationary Bike'], ARRAY['Changing Rooms','Showers','Lockers','Water Cooler'], 4, 180),
  ('618721', 'Studio', ARRAY[]::text[], ARRAY['Water Cooler'], null, null),
  ('618721', 'Swimming Pool', ARRAY[]::text[], ARRAY['Changing Rooms','Showers','Lockers'], 1.5, null),
  ('618721', 'Tennis Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 3, null),
  ('619229', 'Futsal / Street Soccer Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 4, null),
  ('619229', 'Gymnasium', ARRAY['Treadmill','Dumbbells','Bench Press','Cable Machine','Stationary Bike'], ARRAY['Changing Rooms','Showers','Lockers','Water Cooler'], 4, 180),
  ('619229', 'Squash Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 6, null),
  ('619229', 'Swimming Pool', ARRAY[]::text[], ARRAY['Changing Rooms','Showers','Lockers'], 2, null),
  ('619229', 'Tennis Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 3, null),
  ('619529', 'Gymnasium', ARRAY['Treadmill','Dumbbells','Bench Press','Cable Machine','Stationary Bike'], ARRAY['Changing Rooms','Showers','Lockers','Water Cooler'], 3, 120),
  ('619618', 'Football Field', ARRAY[]::text[], ARRAY['Bleachers','Water Cooler','Toilets'], null, null),
  ('619618', 'Futsal / Street Soccer Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 6, null),
  ('619618', 'Handball Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 8, null),
  ('619618', 'Hockey Field', ARRAY[]::text[], ARRAY['Bleachers','Water Cooler','Toilets'], null, null),
  ('619618', 'Pickleball Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 4, null),
  ('619618', 'Studio', ARRAY[]::text[], ARRAY['Water Cooler'], null, null),
  ('619618', 'Tennis Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 6, null),
  ('619651', 'Badminton Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 8, null),
  ('619651', 'Basketball Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 3, null),
  ('619651', 'Cricket Field / Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 4, null),
  ('619651', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('619651', 'Football Field', ARRAY[]::text[], ARRAY['Bleachers','Water Cooler','Toilets'], null, null),
  ('619651', 'Gymnasium', ARRAY['Treadmill','Dumbbells','Bench Press','Cable Machine','Stationary Bike'], ARRAY['Changing Rooms','Showers','Lockers','Water Cooler'], 6, 300),
  ('619698', 'Futsal / Street Soccer Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 3, null),
  ('619698', 'Gymnasium', ARRAY['Treadmill','Dumbbells','Bench Press','Cable Machine','Stationary Bike'], ARRAY['Changing Rooms','Showers','Lockers','Water Cooler'], 3, 120),
  ('619821', 'Athletics Track', ARRAY[]::text[], ARRAY['Bleachers','Water Cooler','Toilets'], null, null),
  ('619821', 'Football Field', ARRAY[]::text[], ARRAY['Bleachers','Water Cooler','Toilets'], null, null),
  ('627615', 'Basketball Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 8, null),
  ('627615', 'Futsal / Street Soccer Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 3, null),
  ('627615', 'Gymnasium', ARRAY['Treadmill','Dumbbells','Bench Press','Cable Machine','Stationary Bike'], ARRAY['Changing Rooms','Showers','Lockers','Water Cooler'], 3, 120),
  ('627615', 'Swimming Pool', ARRAY[]::text[], ARRAY['Changing Rooms','Showers','Lockers'], 1.5, null),
  ('627880', 'Cue Sports Table', ARRAY[]::text[], ARRAY['Water Cooler'], null, null),
  ('627880', 'Gymnasium', ARRAY['Treadmill','Dumbbells','Bench Press','Cable Machine','Stationary Bike'], ARRAY['Changing Rooms','Showers','Lockers','Water Cooler'], 6, 300),
  ('628054', 'Gymnasium', ARRAY['Treadmill','Dumbbells','Bench Press','Cable Machine','Stationary Bike'], ARRAY['Changing Rooms','Showers','Lockers','Water Cooler'], 2.5, 90),
  ('628088', 'Badminton Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 4, null),
  ('628088', 'Basketball Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 5, null),
  ('628088', 'Cricket Field / Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 6, null),
  ('628088', 'Football Field', ARRAY[]::text[], ARRAY['Bleachers','Water Cooler','Toilets'], null, null),
  ('628088', 'Futsal / Street Soccer Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 3, null),
  ('628088', 'Sepak Takraw Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 4, null),
  ('628088', 'Volleyball Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 5, null),
  ('628134', 'Studio', ARRAY[]::text[], ARRAY['Water Cooler'], null, null),
  ('628134', 'Table Tennis Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 8, null),
  ('628277', 'Gymnasium', ARRAY['Treadmill','Dumbbells','Bench Press','Cable Machine','Stationary Bike'], ARRAY['Changing Rooms','Showers','Lockers','Water Cooler'], 2.5, 90),
  ('628413', 'Gymnasium', ARRAY['Treadmill','Dumbbells','Bench Press','Cable Machine','Stationary Bike'], ARRAY['Changing Rooms','Showers','Lockers','Water Cooler'], 3, 120),
  ('628413', 'Studio', ARRAY[]::text[], ARRAY['Water Cooler'], null, null),
  ('636956', 'Archery Range', ARRAY[]::text[], ARRAY['Water Cooler'], null, null),
  ('636956', 'Cricket Field / Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 8, null),
  ('636956', 'Tennis Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 3, null),
  ('636956', 'Wall Climbing', ARRAY[]::text[], ARRAY['Water Cooler'], null, null),
  ('637616', 'Badminton Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 5, null),
  ('637616', 'Basketball Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 6, null),
  ('637616', 'Gymnasium', ARRAY['Treadmill','Dumbbells','Bench Press','Cable Machine','Stationary Bike'], ARRAY['Changing Rooms','Showers','Lockers','Water Cooler'], 6, 300),
  ('637616', 'Handball Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 3, null),
  ('637616', 'Hockey Field', ARRAY[]::text[], ARRAY['Bleachers','Water Cooler','Toilets'], null, null),
  ('637616', 'Netball Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 5, null),
  ('637616', 'Sepak Takraw Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 6, null),
  ('637616', 'Studio', ARRAY[]::text[], ARRAY['Water Cooler'], null, null),
  ('637616', 'Swimming Pool', ARRAY[]::text[], ARRAY['Changing Rooms','Showers','Lockers'], 1.5, null),
  ('637616', 'Tennis Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 4, null),
  ('637616', 'Volleyball Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 5, null),
  ('637978', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('638366', 'Badminton Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 8, null),
  ('638366', 'Gymnasium', ARRAY['Treadmill','Dumbbells','Bench Press','Cable Machine','Stationary Bike'], ARRAY['Changing Rooms','Showers','Lockers','Water Cooler'], 2.5, 90),
  ('638366', 'Studio', ARRAY[]::text[], ARRAY['Water Cooler'], null, null),
  ('638366', 'Swimming Pool', ARRAY[]::text[], ARRAY['Changing Rooms','Showers','Lockers'], 1, null),
  ('638404', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('638404', 'Gymnasium', ARRAY['Treadmill','Dumbbells','Bench Press','Cable Machine','Stationary Bike'], ARRAY['Changing Rooms','Showers','Lockers','Water Cooler'], 6, 300),
  ('638404', 'Pickleball Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 3, null),
  ('638404', 'Swimming Pool', ARRAY[]::text[], ARRAY['Changing Rooms','Showers','Lockers'], 1, null),
  ('638483', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('638483', 'Gymnasium', ARRAY['Treadmill','Dumbbells','Bench Press','Cable Machine','Stationary Bike'], ARRAY['Changing Rooms','Showers','Lockers','Water Cooler'], 5, 240),
  ('638483', 'Table Tennis Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 8, null)
on conflict (postal_code, facility_type) do update
set
  equipment = excluded.equipment,
  amenities = excluded.amenities,
  day_pass_price = excluded.day_pass_price,
  membership_price = excluded.membership_price;
