insert into public.gym_enrichments (
  postal_code,
  facility_type,
  equipment,
  amenities,
  day_pass_price,
  membership_price
)
values
  ('760126', 'Jogging Track', ARRAY[]::text[], ARRAY['Bleachers','Water Cooler','Toilets'], null, null),
  ('760128', 'Badminton Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 4, null),
  ('760130', 'Badminton Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 5, null),
  ('760134', 'Sepak Takraw Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 6, null),
  ('760135', 'Badminton Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 8, null),
  ('760139', 'Badminton Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 3, null),
  ('760139', 'Basketball Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 4, null),
  ('760141', 'Table Tennis Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 5, null),
  ('760147', 'Basketball Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 6, null),
  ('760148', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('760151', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('760152', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('760155', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('760158', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('760159', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('760160', 'Badminton Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 3, null),
  ('760161', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('760165', 'Badminton Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 5, null),
  ('760165', 'Basketball Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 6, null),
  ('760165', 'Sepak Takraw Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 8, null),
  ('760166', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('760167', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('760173', 'Badminton Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 5, null),
  ('760175', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('760207', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('760210', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('760213', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('760216', 'Badminton Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 5, null),
  ('760216', 'Basketball Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 6, null),
  ('760216', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('760216', 'Pickleball Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 3, null),
  ('760216', 'Sepak Takraw Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 4, null),
  ('760216', 'Volleyball Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 5, null),
  ('760220', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('760221', 'Basketball Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 8, null),
  ('760225', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('760235', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('760240', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('760247', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('760259', 'Badminton Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 8, null),
  ('760259', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('760259', 'Pickleball Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 4, null),
  ('760259', 'Sepak Takraw Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 5, null),
  ('760259', 'Volleyball Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 6, null),
  ('760264', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('760265', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('760267', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('760268', 'Badminton Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 5, null),
  ('760278', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('760281', 'Basketball Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 8, null),
  ('760282', 'Badminton Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 3, null),
  ('760282', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('760282', 'Futsal / Street Soccer Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 5, null),
  ('760288', 'Basketball Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 6, null),
  ('760290', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('760299', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('760304', 'Badminton Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 4, null),
  ('760304', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('760306', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('760312', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('760321', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('760323', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('760324', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('760328', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('760329', 'Basketball Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 8, null),
  ('760329', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('760329', 'Futsal / Street Soccer Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 4, null),
  ('760331', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('760333', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('760343', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('760343', 'Jogging Track', ARRAY[]::text[], ARRAY['Bleachers','Water Cooler','Toilets'], null, null),
  ('760346', 'Basketball Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 4, null),
  ('760346', 'Cycling Track', ARRAY[]::text[], ARRAY['Bleachers','Water Cooler','Toilets'], null, null),
  ('760346', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('760346', 'Jogging Track', ARRAY[]::text[], ARRAY['Bleachers','Water Cooler','Toilets'], null, null),
  ('760349', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('760350', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('760364', 'Badminton Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 5, null),
  ('760364', 'Pickleball Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 6, null),
  ('760367', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('760385', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('760385', 'Futsal / Street Soccer Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 4, null),
  ('760388', 'Basketball Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 5, null),
  ('760388', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('760390', 'Badminton Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 8, null),
  ('760390', 'Basketball Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 3, null),
  ('760390', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('760394', 'Badminton Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 5, null),
  ('760394', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('760394', 'Sepak Takraw Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 8, null),
  ('760394', 'Table tennis Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 3, null),
  ('760395', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('760397', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('760398', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('760402', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('760403', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('760404', 'Badminton Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 4, null),
  ('760404', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('760404', 'Sepak Takraw Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 6, null),
  ('760407', 'Basketball Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 8, null),
  ('760407', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('760407', 'Jogging Track', ARRAY[]::text[], ARRAY['Bleachers','Water Cooler','Toilets'], null, null),
  ('760409', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('760411', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('760417', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('760423', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('760425', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('760432', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('760433', 'Badminton Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 6, null),
  ('760433', 'Sepak Takraw Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 8, null),
  ('760435', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('760438', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('760439', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('760443', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('760446', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('760447', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('760448', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('760449', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('760453', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('760454', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('760457', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('760602', 'Basketball Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 4, null),
  ('760604', 'Badminton Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 5, null),
  ('760605', 'Badminton Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 6, null),
  ('760605', 'Basketball Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 8, null),
  ('760605', 'Sepak Takraw Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 3, null),
  ('760609', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('760618', 'Badminton Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 5, null),
  ('760618', 'Basketball Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 6, null),
  ('760618', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('760618', 'Sepak Takraw Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 3, null),
  ('760619', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('760624', 'Badminton Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 5, null),
  ('760624', 'Basketball Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 6, null),
  ('760624', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('760624', 'Sepak Takraw Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 3, null),
  ('760626', 'Badminton Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 4, null),
  ('760626', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('760636', 'Basketball Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 6, null),
  ('760637', 'Badminton Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 8, null),
  ('760637', 'Basketball Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 3, null),
  ('760637', 'Sepak Takraw Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 4, null),
  ('760642', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('760645', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('760659', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('760662', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('760662', 'Futsal / Street Soccer Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 4, null),
  ('760663', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('760664', 'Badminton Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 6, null),
  ('760705', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('760711', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('760716', 'Badminton Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 4, null),
  ('760716', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('760723', 'Badminton Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 6, null),
  ('760723', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('760724', 'Badminton Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 3, null),
  ('760724', 'Sepak Takraw Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 4, null),
  ('760724', 'Volleyball Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 5, null),
  ('760733', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('760736', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('760737', 'Badminton Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 3, null),
  ('760737', 'Basketball Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 4, null),
  ('760737', 'Sepak Takraw Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 5, null),
  ('760740', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('760747', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('760749', 'Studio', ARRAY[]::text[], ARRAY['Water Cooler'], null, null),
  ('760753', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('760755', 'Badminton Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 5, null),
  ('760755', 'Basketball Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 6, null),
  ('760755', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('760757', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('760759', 'Petanque Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 4, null),
  ('760761', 'Basketball Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 5, null),
  ('760761', 'Futsal / Street Soccer Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 6, null),
  ('760765', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('760770', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('760776', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('760780', 'Badminton Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 5, null),
  ('760780', 'Sepak Takraw Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 6, null),
  ('760780', 'Volleyball Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 8, null),
  ('760785', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('760792', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('760800', 'Gymnasium', ARRAY['Treadmill','Dumbbells','Bench Press','Cable Machine','Stationary Bike'], ARRAY['Changing Rooms','Showers','Lockers','Water Cooler'], 4, 180),
  ('760800', 'Jogging track', ARRAY[]::text[], ARRAY['Bleachers','Water Cooler','Toilets'], null, null),
  ('760800', 'Swimming Pool', ARRAY[]::text[], ARRAY['Changing Rooms','Showers','Lockers'], 1, null),
  ('760800', 'Tennis Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 3, null),
  ('760802', 'Badminton Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 4, null),
  ('760802', 'Table Tennis Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 5, null),
  ('760809', 'Badminton Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 6, null),
  ('760809', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('760809', 'Futsal / Street Soccer Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 3, null),
  ('760810', 'Football Field', ARRAY[]::text[], ARRAY['Bleachers','Water Cooler','Toilets'], null, null),
  ('760817', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('760823', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('760824', 'Badminton Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 8, null),
  ('760824', 'Table Tennis Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 3, null),
  ('760826', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('760830', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('760833', 'Badminton Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 6, null),
  ('760834', 'Badminton Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 8, null),
  ('760838', 'Badminton Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 3, null),
  ('760838', 'Basketball Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 4, null),
  ('760838', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('760838', 'Jogging Track', ARRAY[]::text[], ARRAY['Bleachers','Water Cooler','Toilets'], null, null),
  ('760838', 'Sepak Takraw Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 8, null),
  ('760840', 'Table Tennis Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 3, null),
  ('760852', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('760853', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('760862', 'Badminton Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 6, null),
  ('760862', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('760864', 'Badminton Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 3, null),
  ('760865', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('760867', 'Badminton Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 5, null),
  ('760868', 'Badminton Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 6, null),
  ('760868', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('760874', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('760875', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('760879', 'Badminton Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 5, null),
  ('760879', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('760930', 'Gymnasium', ARRAY['Treadmill','Dumbbells','Bench Press','Cable Machine','Stationary Bike'], ARRAY['Changing Rooms','Showers','Lockers','Water Cooler'], 6, 300),
  ('760930', 'Studio', ARRAY[]::text[], ARRAY['Water Cooler'], null, null),
  ('760934', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('760935', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('761318', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('761347', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('761355', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('761426', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('761429', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('761461', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('761468', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('761472', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('761476', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('761477', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('761478', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('761479', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('761506', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('761513', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('761633', 'Badminton Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 5, null),
  ('761633', 'Basketball Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 6, null),
  ('761633', 'Sepak Takraw Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 8, null),
  ('762316', 'Badminton Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 3, null),
  ('762316', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('762316', 'Sepak Takraw Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 5, null),
  ('762316', 'Volleyball Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 6, null),
  ('762334', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('762429', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('762430', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('762432', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('762462', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('762465', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('762466', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('762475', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('762476', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('762508', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('762512', 'Badminton Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 8, null),
  ('762512', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('762674', 'Badminton Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 4, null),
  ('762701', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('762813', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('763315', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('763342', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('763426', 'Badminton Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 4, null),
  ('763426', 'Sepak Takraw Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 5, null),
  ('763462', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('763462', 'Jogging Track', ARRAY[]::text[], ARRAY['Bleachers','Water Cooler','Toilets'], null, null),
  ('763478', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('763479', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('763502', 'Badminton Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 5, null),
  ('763502', 'Basketball Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 6, null),
  ('763502', 'Jogging Track', ARRAY[]::text[], ARRAY['Bleachers','Water Cooler','Toilets'], null, null),
  ('764334', 'Badminton Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 3, null),
  ('764334', 'Sepak Takraw Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 4, null),
  ('764424', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('764426', 'Badminton Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 6, null),
  ('764504', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('764675', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('767944', 'Bowling Alley', ARRAY[]::text[], ARRAY['Water Cooler'], null, null),
  ('767963', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('767963', 'Golf', ARRAY[]::text[], ARRAY['Water Cooler'], null, null),
  ('767963', 'Gymnasium', ARRAY['Treadmill','Dumbbells','Bench Press','Cable Machine','Stationary Bike'], ARRAY['Changing Rooms','Showers','Lockers','Water Cooler'], 6, 300),
  ('767963', 'Jogging Track', ARRAY[]::text[], ARRAY['Bleachers','Water Cooler','Toilets'], null, null),
  ('767963', 'Studio', ARRAY[]::text[], ARRAY['Water Cooler'], null, null),
  ('767963', 'Swimming Pool', ARRAY[]::text[], ARRAY['Changing Rooms','Showers','Lockers'], 2, null),
  ('767963', 'Tennis Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 6, null),
  ('767996', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('767996', 'Gymnasium', ARRAY['Treadmill','Dumbbells','Bench Press','Cable Machine','Stationary Bike'], ARRAY['Changing Rooms','Showers','Lockers','Water Cooler'], 2.5, 90),
  ('767996', 'Jogging Track', ARRAY[]::text[], ARRAY['Bleachers','Water Cooler','Toilets'], null, null),
  ('767996', 'Studio', ARRAY[]::text[], ARRAY['Water Cooler'], null, null),
  ('767996', 'Swimming Pool', ARRAY[]::text[], ARRAY['Changing Rooms','Showers','Lockers'], 1, null),
  ('767996', 'Tennis Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 8, null),
  ('768004', 'Basketball Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 3, null),
  ('768004', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('768004', 'Gymnasium', ARRAY['Treadmill','Dumbbells','Bench Press','Cable Machine','Stationary Bike'], ARRAY['Changing Rooms','Showers','Lockers','Water Cooler'], 4, 180),
  ('768004', 'Jogging Track', ARRAY[]::text[], ARRAY['Bleachers','Water Cooler','Toilets'], null, null),
  ('768004', 'Studio', ARRAY[]::text[], ARRAY['Water Cooler'], null, null),
  ('768004', 'Swimming Pool', ARRAY[]::text[], ARRAY['Changing Rooms','Showers','Lockers'], 2.5, null),
  ('768004', 'Tennis Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 4, null),
  ('768019', 'Gymnasium', ARRAY['Treadmill','Dumbbells','Bench Press','Cable Machine','Stationary Bike'], ARRAY['Changing Rooms','Showers','Lockers','Water Cooler'], 4, 180),
  ('768039', 'Badminton Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 6, null),
  ('768039', 'Basketball Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 8, null),
  ('768039', 'Football Field', ARRAY[]::text[], ARRAY['Bleachers','Water Cooler','Toilets'], null, null),
  ('768039', 'Gymnasium', ARRAY['Treadmill','Dumbbells','Bench Press','Cable Machine','Stationary Bike'], ARRAY['Changing Rooms','Showers','Lockers','Water Cooler'], 3, 120),
  ('768039', 'Jogging Track', ARRAY[]::text[], ARRAY['Bleachers','Water Cooler','Toilets'], null, null),
  ('768039', 'Swimming Pool', ARRAY[]::text[], ARRAY['Changing Rooms','Showers','Lockers'], 2.5, null),
  ('768039', 'Tennis Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 8, null),
  ('768085', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('768085', 'Gymnasium', ARRAY['Treadmill','Dumbbells','Bench Press','Cable Machine','Stationary Bike'], ARRAY['Changing Rooms','Showers','Lockers','Water Cooler'], 3, 120),
  ('768085', 'Jogging Track', ARRAY[]::text[], ARRAY['Bleachers','Water Cooler','Toilets'], null, null),
  ('768085', 'Studio', ARRAY[]::text[], ARRAY['Water Cooler'], null, null),
  ('768085', 'Swimming Pool', ARRAY[]::text[], ARRAY['Changing Rooms','Showers','Lockers'], 1.5, null),
  ('768085', 'Tennis Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 3, null),
  ('768094', 'Basketball Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 4, null),
  ('768094', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('768094', 'Gymnasium', ARRAY['Treadmill','Dumbbells','Bench Press','Cable Machine','Stationary Bike'], ARRAY['Changing Rooms','Showers','Lockers','Water Cooler'], 5, 240),
  ('768094', 'Jogging Track', ARRAY[]::text[], ARRAY['Bleachers','Water Cooler','Toilets'], null, null),
  ('768094', 'Swimming Pool', ARRAY[]::text[], ARRAY['Changing Rooms','Showers','Lockers'], 2.5, null),
  ('768094', 'Tennis Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 4, null),
  ('768101', 'Gymnasium', ARRAY['Treadmill','Dumbbells','Bench Press','Cable Machine','Stationary Bike'], ARRAY['Changing Rooms','Showers','Lockers','Water Cooler'], 4, 180),
  ('768101', 'Swimming Pool', ARRAY[]::text[], ARRAY['Changing Rooms','Showers','Lockers'], 2, null),
  ('768104', 'Basketball Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 8, null),
  ('768104', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('768104', 'Gymnasium', ARRAY['Treadmill','Dumbbells','Bench Press','Cable Machine','Stationary Bike'], ARRAY['Changing Rooms','Showers','Lockers','Water Cooler'], 3, 120),
  ('768104', 'Jogging Track', ARRAY[]::text[], ARRAY['Bleachers','Water Cooler','Toilets'], null, null),
  ('768104', 'Studio', ARRAY[]::text[], ARRAY['Water Cooler'], null, null),
  ('768104', 'Swimming Pool', ARRAY[]::text[], ARRAY['Changing Rooms','Showers','Lockers'], 1, null),
  ('768116', 'Basketball Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 3, null),
  ('768116', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('768116', 'Gymnasium', ARRAY['Treadmill','Dumbbells','Bench Press','Cable Machine','Stationary Bike'], ARRAY['Changing Rooms','Showers','Lockers','Water Cooler'], 4, 180),
  ('768116', 'Jogging Track', ARRAY[]::text[], ARRAY['Bleachers','Water Cooler','Toilets'], null, null),
  ('768116', 'Swimming Pool', ARRAY[]::text[], ARRAY['Changing Rooms','Showers','Lockers'], 1.5, null),
  ('768123', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('768123', 'Gymnasium', ARRAY['Treadmill','Dumbbells','Bench Press','Cable Machine','Stationary Bike'], ARRAY['Changing Rooms','Showers','Lockers','Water Cooler'], 3, 120),
  ('768123', 'Jogging Track', ARRAY[]::text[], ARRAY['Bleachers','Water Cooler','Toilets'], null, null),
  ('768123', 'Swimming Pool', ARRAY[]::text[], ARRAY['Changing Rooms','Showers','Lockers'], 1.5, null),
  ('768123', 'Tennis Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 8, null),
  ('768162', 'Cue Sports Table', ARRAY[]::text[], ARRAY['Water Cooler'], null, null),
  ('768162', 'Golf', ARRAY[]::text[], ARRAY['Water Cooler'], null, null),
  ('768162', 'Gymnasium', ARRAY['Treadmill','Dumbbells','Bench Press','Cable Machine','Stationary Bike'], ARRAY['Changing Rooms','Showers','Lockers','Water Cooler'], 4, 180),
  ('768162', 'Shooting Range', ARRAY[]::text[], ARRAY['Water Cooler'], null, null),
  ('768162', 'Squash Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 8, null),
  ('768162', 'Studio', ARRAY[]::text[], ARRAY['Water Cooler'], null, null),
  ('768162', 'Swimming Pool', ARRAY[]::text[], ARRAY['Changing Rooms','Showers','Lockers'], 1.5, null),
  ('768162', 'Table Tennis Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 5, null),
  ('768162', 'Tennis Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 6, null),
  ('768430', 'Table Tennis Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 8, null),
  ('768432', 'Golf', ARRAY[]::text[], ARRAY['Water Cooler'], null, null),
  ('768432', 'Gymnasium', ARRAY['Treadmill','Dumbbells','Bench Press','Cable Machine','Stationary Bike'], ARRAY['Changing Rooms','Showers','Lockers','Water Cooler'], 3, 120),
  ('768432', 'Jogging track', ARRAY[]::text[], ARRAY['Bleachers','Water Cooler','Toilets'], null, null),
  ('768432', 'Swimming Pool', ARRAY[]::text[], ARRAY['Changing Rooms','Showers','Lockers'], 1, null),
  ('768432', 'Tennis Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 8, null),
  ('768435', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('768435', 'Gymnasium', ARRAY['Treadmill','Dumbbells','Bench Press','Cable Machine','Stationary Bike'], ARRAY['Changing Rooms','Showers','Lockers','Water Cooler'], 3, 120),
  ('768435', 'Swimming Pool', ARRAY[]::text[], ARRAY['Changing Rooms','Showers','Lockers'], 1, null),
  ('768435', 'Tennis Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 6, null),
  ('768446', 'Badminton Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 8, null),
  ('768446', 'Basketball Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 3, null),
  ('768446', 'Cue Sports Table', ARRAY[]::text[], ARRAY['Water Cooler'], null, null),
  ('768446', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('768446', 'Golf', ARRAY[]::text[], ARRAY['Water Cooler'], null, null),
  ('768446', 'Gymnasium', ARRAY['Treadmill','Dumbbells','Bench Press','Cable Machine','Stationary Bike'], ARRAY['Changing Rooms','Showers','Lockers','Water Cooler'], 6, 300),
  ('768446', 'Sepak Takraw Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 3, null),
  ('768446', 'Squash Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 4, null),
  ('768446', 'Swimming Pool', ARRAY[]::text[], ARRAY['Changing Rooms','Showers','Lockers'], 2, null),
  ('768446', 'Tennis Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 6, null),
  ('768454', 'Football Field', ARRAY[]::text[], ARRAY['Bleachers','Water Cooler','Toilets'], null, null),
  ('768454', 'Studio', ARRAY[]::text[], ARRAY['Water Cooler'], null, null),
  ('768455', 'Badminton Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 4, null),
  ('768515', 'Badminton Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 5, null),
  ('768515', 'Basketball Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 6, null),
  ('768515', 'Gymnasium', ARRAY['Treadmill','Dumbbells','Bench Press','Cable Machine','Stationary Bike'], ARRAY['Changing Rooms','Showers','Lockers','Water Cooler'], 6, 300),
  ('768515', 'Netball Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 3, null),
  ('768515', 'Studio', ARRAY[]::text[], ARRAY['Water Cooler'], null, null),
  ('768516', 'Badminton Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 5, null),
  ('768516', 'Basketball Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 6, null),
  ('768516', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('768516', 'Football Field', ARRAY[]::text[], ARRAY['Bleachers','Water Cooler','Toilets'], null, null),
  ('768516', 'Gymnasium', ARRAY['Treadmill','Dumbbells','Bench Press','Cable Machine','Stationary Bike'], ARRAY['Changing Rooms','Showers','Lockers','Water Cooler'], 3, 120),
  ('768516', 'Netball Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 5, null),
  ('768516', 'Table Tennis Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 6, null),
  ('768516', 'Volleyball Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 8, null),
  ('768516', 'Wall Climbing', ARRAY[]::text[], ARRAY['Water Cooler'], null, null),
  ('768547', 'Badminton Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 4, null),
  ('768547', 'Basketball Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 5, null),
  ('768547', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('768547', 'Football Field', ARRAY[]::text[], ARRAY['Bleachers','Water Cooler','Toilets'], null, null),
  ('768547', 'Gymnasium', ARRAY['Treadmill','Dumbbells','Bench Press','Cable Machine','Stationary Bike'], ARRAY['Changing Rooms','Showers','Lockers','Water Cooler'], 2.5, 90),
  ('768547', 'Netball Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 4, null),
  ('768547', 'Table Tennis Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 5, null),
  ('768547', 'Volleyball Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 6, null),
  ('768578', 'Badminton Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 8, null),
  ('768578', 'Basketball Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 3, null),
  ('768578', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('768578', 'Gymnasium', ARRAY['Treadmill','Dumbbells','Bench Press','Cable Machine','Stationary Bike'], ARRAY['Changing Rooms','Showers','Lockers','Water Cooler'], 4, 180),
  ('768578', 'Netball Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 6, null),
  ('768578', 'Studio', ARRAY[]::text[], ARRAY['Water Cooler'], null, null),
  ('768578', 'Volleyball Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 3, null),
  ('768610', 'Badminton Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 4, null),
  ('768610', 'Basketball Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 5, null),
  ('768610', 'Football Field', ARRAY[]::text[], ARRAY['Bleachers','Water Cooler','Toilets'], null, null),
  ('768610', 'Gymnasium', ARRAY['Treadmill','Dumbbells','Bench Press','Cable Machine','Stationary Bike'], ARRAY['Changing Rooms','Showers','Lockers','Water Cooler'], 6, 300)
on conflict (postal_code, facility_type) do update
set
  equipment = excluded.equipment,
  amenities = excluded.amenities,
  day_pass_price = excluded.day_pass_price,
  membership_price = excluded.membership_price;
