insert into public.gym_enrichments (
  postal_code,
  facility_type,
  equipment,
  amenities,
  day_pass_price,
  membership_price
)
values
  ('689579', 'Gymnasium', ARRAY['Treadmill','Dumbbells','Bench Press','Cable Machine','Stationary Bike'], ARRAY['Changing Rooms','Showers','Lockers','Water Cooler'], 2.5, 90),
  ('689579', 'Swimming Pool', ARRAY[]::text[], ARRAY['Changing Rooms','Showers','Lockers'], 1.5, null),
  ('689621', 'Badminton Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 5, null),
  ('689621', 'Football Field', ARRAY[]::text[], ARRAY['Bleachers','Water Cooler','Toilets'], null, null),
  ('689621', 'Gymnasium', ARRAY['Treadmill','Dumbbells','Bench Press','Cable Machine','Stationary Bike'], ARRAY['Changing Rooms','Showers','Lockers','Water Cooler'], 6, 300),
  ('689621', 'Netball Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 3, null),
  ('689621', 'Studio', ARRAY[]::text[], ARRAY['Water Cooler'], null, null),
  ('689668', 'Badminton Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 5, null),
  ('689668', 'Basketball Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 6, null),
  ('689668', 'Golf', ARRAY[]::text[], ARRAY['Water Cooler'], null, null),
  ('689668', 'Gymnasium', ARRAY['Treadmill','Dumbbells','Bench Press','Cable Machine','Stationary Bike'], ARRAY['Changing Rooms','Showers','Lockers','Water Cooler'], 2.5, 90),
  ('689668', 'Squash Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 4, null),
  ('689668', 'Swimming Pool', ARRAY[]::text[], ARRAY['Changing Rooms','Showers','Lockers'], 1, null),
  ('689668', 'Tennis Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 6, null),
  ('689673', 'Basketball Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 8, null),
  ('689673', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('689673', 'Golf', ARRAY[]::text[], ARRAY['Water Cooler'], null, null),
  ('689673', 'Gymnasium', ARRAY['Treadmill','Dumbbells','Bench Press','Cable Machine','Stationary Bike'], ARRAY['Changing Rooms','Showers','Lockers','Water Cooler'], 4, 180),
  ('689673', 'Squash Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 6, null),
  ('689673', 'Swimming Pool', ARRAY[]::text[], ARRAY['Changing Rooms','Showers','Lockers'], 2.5, null),
  ('689673', 'Tennis Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 3, null),
  ('689686', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('689686', 'Gymnasium', ARRAY['Treadmill','Dumbbells','Bench Press','Cable Machine','Stationary Bike'], ARRAY['Changing Rooms','Showers','Lockers','Water Cooler'], 4, 180),
  ('689686', 'Swimming Pool', ARRAY[]::text[], ARRAY['Changing Rooms','Showers','Lockers'], 2.5, null),
  ('689687', 'Badminton Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 8, null),
  ('689687', 'Bowling Alley', ARRAY[]::text[], ARRAY['Water Cooler'], null, null),
  ('689687', 'Gymnasium', ARRAY['Treadmill','Dumbbells','Bench Press','Cable Machine','Stationary Bike'], ARRAY['Changing Rooms','Showers','Lockers','Water Cooler'], 3, 120),
  ('689687', 'Table tennis Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 5, null),
  ('689715', 'Gymnasium', ARRAY['Treadmill','Dumbbells','Bench Press','Cable Machine','Stationary Bike'], ARRAY['Changing Rooms','Showers','Lockers','Water Cooler'], 5, 240),
  ('689719', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('689719', 'Jogging Track', ARRAY[]::text[], ARRAY['Bleachers','Water Cooler','Toilets'], null, null),
  ('689762', 'Badminton Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 4, null),
  ('689762', 'Basketball Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 5, null),
  ('689762', 'Football Field', ARRAY[]::text[], ARRAY['Bleachers','Water Cooler','Toilets'], null, null),
  ('689762', 'Netball Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 8, null),
  ('689762', 'Studio', ARRAY[]::text[], ARRAY['Water Cooler'], null, null),
  ('689809', 'Badminton Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 4, null),
  ('689809', 'Football Field', ARRAY[]::text[], ARRAY['Bleachers','Water Cooler','Toilets'], null, null),
  ('689814', 'Badminton Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 6, null),
  ('689814', 'Basketball Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 8, null),
  ('689814', 'Gymnasium', ARRAY['Treadmill','Dumbbells','Bench Press','Cable Machine','Stationary Bike'], ARRAY['Changing Rooms','Showers','Lockers','Water Cooler'], 2.5, 90),
  ('689814', 'Studio', ARRAY[]::text[], ARRAY['Water Cooler'], null, null),
  ('689814', 'Volleyball Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 5, null),
  ('689879', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('689879', 'Gymnasium', ARRAY['Treadmill','Dumbbells','Bench Press','Cable Machine','Stationary Bike'], ARRAY['Changing Rooms','Showers','Lockers','Water Cooler'], 6, 300),
  ('689879', 'Swimming Pool', ARRAY[]::text[], ARRAY['Changing Rooms','Showers','Lockers'], 1.5, null),
  ('689905', 'Badminton Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 4, null),
  ('689905', 'Basketball Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 5, null),
  ('689905', 'Studio', ARRAY[]::text[], ARRAY['Water Cooler'], null, null),
  ('689964', 'Futsal / Street Soccer Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 8, null),
  ('689964', 'Gymnasium', ARRAY['Treadmill','Dumbbells','Bench Press','Cable Machine','Stationary Bike'], ARRAY['Changing Rooms','Showers','Lockers','Water Cooler'], 2.5, 90),
  ('689964', 'Swimming Pool', ARRAY[]::text[], ARRAY['Changing Rooms','Showers','Lockers'], 2.5, null),
  ('689964', 'Wall Climbing', ARRAY[]::text[], ARRAY['Water Cooler'], null, null),
  ('690112', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('690117', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('690120', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('690123', 'Badminton Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 4, null),
  ('690123', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('690127', 'Swimming Pool', ARRAY[]::text[], ARRAY['Changing Rooms','Showers','Lockers'], 2, null),
  ('690129', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('690218', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('690223', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('691112', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('691119', 'Badminton Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 6, null),
  ('691131', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('691132', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('691219', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('691224', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('691225', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('692114', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('692127', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('692220', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('692221', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('692228', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('692231', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('692235', 'Badminton Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 3, null),
  ('692235', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('692237', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('693111', 'Badminton Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 6, null),
  ('693126', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('693131', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('693132', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('693133', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('698928', 'Athletics Track', ARRAY[]::text[], ARRAY['Bleachers','Water Cooler','Toilets'], null, null),
  ('698928', 'Badminton Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 8, null),
  ('698928', 'Basketball Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 3, null),
  ('698928', 'Football Field', ARRAY[]::text[], ARRAY['Bleachers','Water Cooler','Toilets'], null, null),
  ('698928', 'Gymnasium', ARRAY['Treadmill','Dumbbells','Bench Press','Cable Machine','Stationary Bike'], ARRAY['Changing Rooms','Showers','Lockers','Water Cooler'], 4, 180),
  ('698928', 'Jogging track', ARRAY[]::text[], ARRAY['Bleachers','Water Cooler','Toilets'], null, null),
  ('698928', 'Shooting Range', ARRAY[]::text[], ARRAY['Water Cooler'], null, null),
  ('698928', 'Swimming Pool', ARRAY[]::text[], ARRAY['Changing Rooms','Showers','Lockers'], 2, null),
  ('698928', 'Table Tennis Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 4, null),
  ('698928', 'Tennis Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 5, null),
  ('698928', 'Wall Climbing', ARRAY[]::text[], ARRAY['Water Cooler'], null, null),
  ('699814', 'Shooting Range', ARRAY[]::text[], ARRAY['Water Cooler'], null, null),
  ('718828', 'Golf', ARRAY[]::text[], ARRAY['Water Cooler'], null, null),
  ('719920', 'Wall Climbing', ARRAY[]::text[], ARRAY['Water Cooler'], null, null),
  ('729749', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('730027', 'Badminton Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 6, null),
  ('730027', 'Futsal / Street Soccer Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 8, null),
  ('730027', 'Gymnasium', ARRAY['Treadmill','Dumbbells','Bench Press','Cable Machine','Stationary Bike'], ARRAY['Changing Rooms','Showers','Lockers','Water Cooler'], 2.5, 90),
  ('730027', 'Sepak Takraw Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 4, null),
  ('730027', 'Table Tennis Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 5, null),
  ('730112', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('730216', 'Gymnasium', ARRAY['Treadmill','Dumbbells','Bench Press','Cable Machine','Stationary Bike'], ARRAY['Changing Rooms','Showers','Lockers','Water Cooler'], 6, 300),
  ('730303', 'Gymnasium', ARRAY['Treadmill','Dumbbells','Bench Press','Cable Machine','Stationary Bike'], ARRAY['Changing Rooms','Showers','Lockers','Water Cooler'], 2.5, 90),
  ('730303', 'Studio', ARRAY[]::text[], ARRAY['Water Cooler'], null, null),
  ('730306', 'Badminton Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 5, null),
  ('730306', 'Basketball Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 6, null),
  ('730306', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('730306', 'Floorball Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 3, null),
  ('730306', 'Jogging Track', ARRAY[]::text[], ARRAY['Bleachers','Water Cooler','Toilets'], null, null),
  ('730306', 'Sepak Takraw Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 5, null),
  ('730501', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('730506', 'Badminton Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 8, null),
  ('730528', 'Badminton Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 3, null),
  ('730528', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('730535', 'Badminton Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 5, null),
  ('730537', 'Badminton Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 6, null),
  ('730537', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('730538', 'Badminton Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 3, null),
  ('730538', 'Table tennis Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 4, null),
  ('730548', 'Gymnasium', ARRAY['Treadmill','Dumbbells','Bench Press','Cable Machine','Stationary Bike'], ARRAY['Changing Rooms','Showers','Lockers','Water Cooler'], 4, 180),
  ('730551', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('730552', 'Badminton Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 8, null),
  ('730552', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('730578', 'Badminton Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 4, null),
  ('730580', 'Badminton Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 5, null),
  ('730580', 'Basketball Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 6, null),
  ('730580', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('730580', 'Jogging Track', ARRAY[]::text[], ARRAY['Bleachers','Water Cooler','Toilets'], null, null),
  ('730580', 'Petanque Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 4, null),
  ('730580', 'Pickleball Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 5, null),
  ('730580', 'Sepak Takraw Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 6, null),
  ('730580', 'Volleyball Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 8, null),
  ('730582', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('730583', 'Futsal / Street Soccer Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 4, null),
  ('730587', 'Badminton Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 5, null),
  ('730602', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('730604', 'Badminton Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 8, null),
  ('730604', 'Sepak Takraw Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 3, null),
  ('730611', 'Badminton Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 4, null),
  ('730611', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('730611', 'Sepak Takraw Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 6, null),
  ('730620', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('730620', 'Jogging Track', ARRAY[]::text[], ARRAY['Bleachers','Water Cooler','Toilets'], null, null),
  ('730622', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('730636', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('730637', 'Badminton Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 6, null),
  ('730637', 'Sepak Takraw Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 8, null),
  ('730639', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('730643', 'Badminton Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 4, null),
  ('730643', 'Sepak Takraw Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 5, null),
  ('730646', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('730648', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('730650', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('730658', 'Basketball Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 4, null),
  ('730659', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('730664', 'Badminton Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 6, null),
  ('730668', 'Badminton Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 8, null),
  ('730668', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('730668', 'Sepak Takraw Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 4, null),
  ('730677', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('730677', 'Futsal / Street Soccer Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 6, null),
  ('730685', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('730685', 'Jogging Track', ARRAY[]::text[], ARRAY['Bleachers','Water Cooler','Toilets'], null, null),
  ('730689', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('730702', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('730704', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('730705', 'Badminton Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 8, null),
  ('730705', 'Sepak Takraw Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 3, null),
  ('730708', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('730711', 'Badminton Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 5, null),
  ('730711', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('730711', 'Sepak Takraw Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 8, null),
  ('730714', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('730718', 'Badminton Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 4, null),
  ('730718', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('730718', 'Sepak Takraw Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 6, null),
  ('730722', 'Badminton Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 8, null),
  ('730722', 'Sepak Takraw Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 3, null),
  ('730723', 'Basketball Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 4, null),
  ('730726', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('730727', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('730730', 'Badminton Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 8, null),
  ('730730', 'Futsal / Street Soccer Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 3, null),
  ('730730', 'Sepak Takraw Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 4, null),
  ('730731', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('730732', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('730733', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('730733', 'Jogging Track', ARRAY[]::text[], ARRAY['Bleachers','Water Cooler','Toilets'], null, null),
  ('730734', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('730735', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('730742', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('730744', 'Badminton Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 8, null),
  ('730744', 'Sepak Takraw Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 3, null),
  ('730755', 'Basketball Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 4, null),
  ('730755', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('730758', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('730759', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('730762', 'Badminton Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 3, null),
  ('730762', 'Sepak Takraw Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 4, null),
  ('730773', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('730777', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('730778', 'Badminton Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 8, null),
  ('730778', 'Sepak Takraw Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 3, null),
  ('730790', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('730796', 'Badminton Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 5, null),
  ('730796', 'Sepak Takraw Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 6, null),
  ('730798', 'Basketball Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 8, null),
  ('730798', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('730801', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('730802', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('730803', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('730806', 'Basketball Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 8, null),
  ('730809', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('730817', 'Badminton Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 4, null),
  ('730817', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('730817', 'Sepak Takraw Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 6, null),
  ('730818', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('730818', 'Golf', ARRAY[]::text[], ARRAY['Water Cooler'], null, null),
  ('730825', 'Badminton Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 4, null),
  ('730825', 'Sepak Takraw Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 5, null),
  ('730827', 'Basketball Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 6, null),
  ('730827', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('730827', 'Jogging Track', ARRAY[]::text[], ARRAY['Bleachers','Water Cooler','Toilets'], null, null),
  ('730828', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('730842', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('730851', 'Badminton Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 6, null),
  ('730851', 'Sepak Takraw Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 8, null),
  ('730852', 'Basketball Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 3, null),
  ('730852', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('730852', 'Petanque Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 5, null),
  ('730857', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('730861', 'Badminton Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 8, null),
  ('730861', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('730861', 'Sepak Takraw Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 4, null),
  ('730868', 'Badminton Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 5, null),
  ('730868', 'Sepak Takraw Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 6, null),
  ('730869', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('730871', 'Gymnasium', ARRAY['Treadmill','Dumbbells','Bench Press','Cable Machine','Stationary Bike'], ARRAY['Changing Rooms','Showers','Lockers','Water Cooler'], 2.5, 90),
  ('730873', 'Badminton Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 4, null),
  ('730873', 'Sepak Takraw Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 5, null),
  ('730874', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('730876', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('730879', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('730881', 'Basketball Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 4, null),
  ('730882', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('730882', 'Futsal / Street Soccer Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 6, null),
  ('730888', 'Gymnasium', ARRAY['Treadmill','Dumbbells','Bench Press','Cable Machine','Stationary Bike'], ARRAY['Changing Rooms','Showers','Lockers','Water Cooler'], 6, 300),
  ('730900', 'Gymnasium', ARRAY['Treadmill','Dumbbells','Bench Press','Cable Machine','Stationary Bike'], ARRAY['Changing Rooms','Showers','Lockers','Water Cooler'], 2.5, 90),
  ('731183', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('731189', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('731628', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('731638', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('731687', 'Badminton Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 3, null),
  ('731694', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('731717', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('731784', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('731785', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('731799', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('732569', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('732571', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('732574', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('732628', 'Badminton Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 8, null),
  ('732682', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('732687', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('732691', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('732693', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('732694', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('732764', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('732783', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('733573', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('733682', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('733683', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('733687', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('733689', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('733690', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('733780', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('733782', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('733784', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('733786', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('734684', 'Badminton Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 5, null),
  ('734693', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('734780', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('734782', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('734785', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('734787', 'Badminton Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 5, null),
  ('734787', 'Sepak Takraw Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 6, null),
  ('735689', 'Badminton Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 8, null),
  ('735690', 'Badminton Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 3, null),
  ('735690', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('737708', 'Badminton Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 5, null),
  ('737708', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('737708', 'Futsal / Street Soccer Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 8, null),
  ('737708', 'Gymnasium', ARRAY['Treadmill','Dumbbells','Bench Press','Cable Machine','Stationary Bike'], ARRAY['Changing Rooms','Showers','Lockers','Water Cooler'], 2.5, 90),
  ('737708', 'Inline Skating Rink', ARRAY[]::text[], ARRAY['Water Cooler'], null, null),
  ('737708', 'Swimming Pool', ARRAY[]::text[], ARRAY['Changing Rooms','Showers','Lockers'], 1.5, null),
  ('737737', 'Gymnasium', ARRAY['Treadmill','Dumbbells','Bench Press','Cable Machine','Stationary Bike'], ARRAY['Changing Rooms','Showers','Lockers','Water Cooler'], 5, 240),
  ('737737', 'Studio', ARRAY[]::text[], ARRAY['Water Cooler'], null, null),
  ('737783', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('737783', 'Gymnasium', ARRAY['Treadmill','Dumbbells','Bench Press','Cable Machine','Stationary Bike'], ARRAY['Changing Rooms','Showers','Lockers','Water Cooler'], 3, 120),
  ('737783', 'Jogging Track', ARRAY[]::text[], ARRAY['Bleachers','Water Cooler','Toilets'], null, null),
  ('737783', 'Studio', ARRAY[]::text[], ARRAY['Water Cooler'], null, null),
  ('737783', 'Swimming Pool', ARRAY[]::text[], ARRAY['Changing Rooms','Showers','Lockers'], 1, null),
  ('737783', 'Tennis Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 3, null),
  ('737803', 'Basketball Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 4, null),
  ('737803', 'Football Field', ARRAY[]::text[], ARRAY['Bleachers','Water Cooler','Toilets'], null, null),
  ('737803', 'Studio', ARRAY[]::text[], ARRAY['Water Cooler'], null, null),
  ('737808', 'Gymnasium', ARRAY['Treadmill','Dumbbells','Bench Press','Cable Machine','Stationary Bike'], ARRAY['Changing Rooms','Showers','Lockers','Water Cooler'], 6, 300),
  ('737808', 'Swimming Pool', ARRAY[]::text[], ARRAY['Changing Rooms','Showers','Lockers'], 2, null),
  ('737808', 'Tennis Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 4, null),
  ('737879', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('737879', 'Gymnasium', ARRAY['Treadmill','Dumbbells','Bench Press','Cable Machine','Stationary Bike'], ARRAY['Changing Rooms','Showers','Lockers','Water Cooler'], 5, 240),
  ('737879', 'Jogging Track', ARRAY[]::text[], ARRAY['Bleachers','Water Cooler','Toilets'], null, null),
  ('737879', 'Studio', ARRAY[]::text[], ARRAY['Water Cooler'], null, null),
  ('737879', 'Swimming Pool', ARRAY[]::text[], ARRAY['Changing Rooms','Showers','Lockers'], 1, null),
  ('737879', 'Tennis Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 5, null),
  ('737888', 'Badminton Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 6, null),
  ('737888', 'Basketball Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 8, null),
  ('737888', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('737888', 'Football Field', ARRAY[]::text[], ARRAY['Bleachers','Water Cooler','Toilets'], null, null),
  ('737888', 'Gymnasium', ARRAY['Treadmill','Dumbbells','Bench Press','Cable Machine','Stationary Bike'], ARRAY['Changing Rooms','Showers','Lockers','Water Cooler'], 4, 180),
  ('737888', 'Netball Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 6, null),
  ('737888', 'Studio', ARRAY[]::text[], ARRAY['Water Cooler'], null, null),
  ('737888', 'Tennis Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 3, null),
  ('737888', 'Volleyball Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 4, null),
  ('737894', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('737894', 'Gymnasium', ARRAY['Treadmill','Dumbbells','Bench Press','Cable Machine','Stationary Bike'], ARRAY['Changing Rooms','Showers','Lockers','Water Cooler'], 5, 240),
  ('737894', 'Tennis Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 8, null),
  ('737902', 'Athletics Track', ARRAY[]::text[], ARRAY['Bleachers','Water Cooler','Toilets'], null, null),
  ('737902', 'Badminton Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 4, null),
  ('737902', 'Basketball Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 5, null),
  ('737902', 'Cue Sports Table', ARRAY[]::text[], ARRAY['Water Cooler'], null, null),
  ('737902', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('737902', 'Football Field', ARRAY[]::text[], ARRAY['Bleachers','Water Cooler','Toilets'], null, null),
  ('737902', 'Futsal / Street Soccer Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 4, null),
  ('737902', 'Gymnasium', ARRAY['Treadmill','Dumbbells','Bench Press','Cable Machine','Stationary Bike'], ARRAY['Changing Rooms','Showers','Lockers','Water Cooler'], 4, 180),
  ('737902', 'Netball Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 6, null),
  ('737902', 'Shooting Range', ARRAY[]::text[], ARRAY['Water Cooler'], null, null),
  ('737902', 'Tennis Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 3, null),
  ('737902', 'Volleyball Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 4, null),
  ('737913', 'Athletics Track', ARRAY[]::text[], ARRAY['Bleachers','Water Cooler','Toilets'], null, null),
  ('737913', 'Badminton Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 6, null),
  ('737913', 'Basketball Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 8, null),
  ('737913', 'Bowling Alley', ARRAY[]::text[], ARRAY['Water Cooler'], null, null),
  ('737913', 'Football Field', ARRAY[]::text[], ARRAY['Bleachers','Water Cooler','Toilets'], null, null),
  ('737913', 'Gymnasium', ARRAY['Treadmill','Dumbbells','Bench Press','Cable Machine','Stationary Bike'], ARRAY['Changing Rooms','Showers','Lockers','Water Cooler'], 4, 180),
  ('737913', 'Netball Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 6, null),
  ('737913', 'Shooting Range', ARRAY[]::text[], ARRAY['Water Cooler'], null, null),
  ('737913', 'Table Tennis Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 3, null),
  ('737916', 'Badminton Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 4, null),
  ('737916', 'Basketball Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 5, null),
  ('737916', 'Football Field', ARRAY[]::text[], ARRAY['Bleachers','Water Cooler','Toilets'], null, null),
  ('737916', 'Gymnasium', ARRAY['Treadmill','Dumbbells','Bench Press','Cable Machine','Stationary Bike'], ARRAY['Changing Rooms','Showers','Lockers','Water Cooler'], 6, 300),
  ('737916', 'Table tennis Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 3, null),
  ('737916', 'Tennis Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 4, null),
  ('737921', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('737921', 'Swimming Pool', ARRAY[]::text[], ARRAY['Changing Rooms','Showers','Lockers'], 2, null),
  ('737921', 'Tennis Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 8, null),
  ('737924', 'Badminton Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 3, null),
  ('737924', 'Basketball Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 4, null),
  ('737924', 'Football Field', ARRAY[]::text[], ARRAY['Bleachers','Water Cooler','Toilets'], null, null),
  ('737924', 'Gymnasium', ARRAY['Treadmill','Dumbbells','Bench Press','Cable Machine','Stationary Bike'], ARRAY['Changing Rooms','Showers','Lockers','Water Cooler'], 5, 240),
  ('737924', 'Netball Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 8, null),
  ('737924', 'Volleyball Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 3, null),
  ('737924', 'Wall Climbing', ARRAY[]::text[], ARRAY['Water Cooler'], null, null),
  ('737936', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('737936', 'Gymnasium', ARRAY['Treadmill','Dumbbells','Bench Press','Cable Machine','Stationary Bike'], ARRAY['Changing Rooms','Showers','Lockers','Water Cooler'], 5, 240),
  ('737936', 'Swimming Pool', ARRAY[]::text[], ARRAY['Changing Rooms','Showers','Lockers'], 1.5, null),
  ('737936', 'Tennis Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 3, null),
  ('737942', 'Badminton Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 4, null),
  ('737942', 'Basketball Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 5, null),
  ('737942', 'Futsal / Street Soccer Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 6, null),
  ('737942', 'Gymnasium', ARRAY['Treadmill','Dumbbells','Bench Press','Cable Machine','Stationary Bike'], ARRAY['Changing Rooms','Showers','Lockers','Water Cooler'], 6, 300),
  ('737942', 'Netball Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 3, null),
  ('737942', 'Studio', ARRAY[]::text[], ARRAY['Water Cooler'], null, null),
  ('737942', 'Volleyball Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 5, null),
  ('738070', 'Badminton Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 6, null),
  ('738070', 'Basketball Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 8, null),
  ('738070', 'Futsal / Street Soccer Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 3, null),
  ('738070', 'Sepak Takraw Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 4, null),
  ('738070', 'Volleyball Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 5, null),
  ('738078', 'Gymnasium', ARRAY['Treadmill','Dumbbells','Bench Press','Cable Machine','Stationary Bike'], ARRAY['Changing Rooms','Showers','Lockers','Water Cooler'], 5, 240),
  ('738079', 'Badminton Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 8, null),
  ('738079', 'Basketball Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 3, null),
  ('738079', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('738079', 'Football Field', ARRAY[]::text[], ARRAY['Bleachers','Water Cooler','Toilets'], null, null),
  ('738079', 'Studio', ARRAY[]::text[], ARRAY['Water Cooler'], null, null),
  ('738079', 'Table Tennis Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 8, null),
  ('738079', 'Volleyball Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 3, null),
  ('738082', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('738085', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('738085', 'Golf', ARRAY[]::text[], ARRAY['Water Cooler'], null, null),
  ('738085', 'Gymnasium', ARRAY['Treadmill','Dumbbells','Bench Press','Cable Machine','Stationary Bike'], ARRAY['Changing Rooms','Showers','Lockers','Water Cooler'], 6, 300),
  ('738085', 'Squash Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 3, null),
  ('738085', 'Swimming Pool', ARRAY[]::text[], ARRAY['Changing Rooms','Showers','Lockers'], 1, null),
  ('738085', 'Tennis Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 5, null),
  ('738098', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('738098', 'Gymnasium', ARRAY['Treadmill','Dumbbells','Bench Press','Cable Machine','Stationary Bike'], ARRAY['Changing Rooms','Showers','Lockers','Water Cooler'], 6, 300)
on conflict (postal_code, facility_type) do update
set
  equipment = excluded.equipment,
  amenities = excluded.amenities,
  day_pass_price = excluded.day_pass_price,
  membership_price = excluded.membership_price;
