insert into public.gym_enrichments (
  postal_code,
  facility_type,
  equipment,
  amenities,
  day_pass_price,
  membership_price
)
values
  ('539842', 'Badminton Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 3, null),
  ('539842', 'Basketball Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 4, null),
  ('539842', 'Football Field', ARRAY[]::text[], ARRAY['Bleachers','Water Cooler','Toilets'], null, null),
  ('539898', 'Basketball Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 6, null),
  ('539898', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('539898', 'Jogging Track', ARRAY[]::text[], ARRAY['Bleachers','Water Cooler','Toilets'], null, null),
  ('539969', 'Swimming Pool', ARRAY[]::text[], ARRAY['Changing Rooms','Showers','Lockers'], 2, null),
  ('540108', 'Badminton Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 5, null),
  ('540109', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('540113', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('540130', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('540131', 'Basketball Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 4, null),
  ('540136', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('540140', 'Badminton Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 6, null),
  ('540143', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('540188', 'Basketball Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 3, null),
  ('540193', 'Studio', ARRAY[]::text[], ARRAY['Water Cooler'], null, null),
  ('540196', 'Badminton Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 5, null),
  ('540196', 'Pickleball Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 6, null),
  ('540224', 'Badminton Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 8, null),
  ('540230', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('540231', 'Badminton Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 4, null),
  ('540236', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('540237', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('540238', 'Badminton Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 8, null),
  ('540246', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('540263', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('540269', 'Badminton Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 5, null),
  ('540269', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('540269', 'Sepak Takraw Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 8, null),
  ('540298', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('540299', 'Basketball Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 4, null),
  ('540339', 'Gymnasium', ARRAY['Treadmill','Dumbbells','Bench Press','Cable Machine','Stationary Bike'], ARRAY['Changing Rooms','Showers','Lockers','Water Cooler'], 4, 180),
  ('541102', 'Futsal / Street Soccer Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 6, null),
  ('541117', 'Basketball Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 8, null),
  ('541124', 'Badminton Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 3, null),
  ('541157', 'Badminton Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 4, null),
  ('541157', 'Pickleball Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 5, null),
  ('541163', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('541178', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('541180', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('541184', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('541190', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('541194', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('541202', 'Badminton Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 8, null),
  ('541208', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('541212', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('541223', 'Badminton Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 5, null),
  ('541227', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('541247', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('541259', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('541278', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('541289', 'Badminton Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 5, null),
  ('541290', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('541293', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('541296', 'Badminton Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 3, null),
  ('541297', 'Badminton Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 4, null),
  ('541356', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('542209', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('542210', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('542216', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('542223', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('542250', 'Badminton Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 5, null),
  ('542258', 'Badminton Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 6, null),
  ('542258', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('542260', 'Badminton Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 3, null),
  ('542260', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('542262', 'Badminton Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 5, null),
  ('542267', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('542267', 'Jogging track', ARRAY[]::text[], ARRAY['Bleachers','Water Cooler','Toilets'], null, null),
  ('542275', 'Badminton Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 3, null),
  ('542275', 'Basketball Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 4, null),
  ('542275', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('542279', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('542281', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('542287', 'Badminton Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 3, null),
  ('542289', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('542292', 'Badminton Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 5, null),
  ('542292', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('542299', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('542316', 'Basketball Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 3, null),
  ('542320', 'Badminton Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 4, null),
  ('542320', 'Basketball Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 5, null),
  ('542320', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('542320', 'Football Field', ARRAY[]::text[], ARRAY['Bleachers','Water Cooler','Toilets'], null, null),
  ('542320', 'Studio', ARRAY[]::text[], ARRAY['Water Cooler'], null, null),
  ('542339', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('543162', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('543162', 'Futsal / Street Soccer Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 6, null),
  ('543201', 'Basketball Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 8, null),
  ('543202', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('543203', 'Badminton Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 4, null),
  ('543203', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('543205', 'Badminton Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 6, null),
  ('543205', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('543211', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('543224', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('543226', 'Badminton Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 5, null),
  ('543226', 'Basketball Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 6, null),
  ('543271', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('543273', 'Basketball Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 3, null),
  ('543282', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('543286', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('543293', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('543302', 'Basketball Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 8, null),
  ('544158', 'Basketball Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 3, null),
  ('544158', 'Gymnasium', ARRAY['Treadmill','Dumbbells','Bench Press','Cable Machine','Stationary Bike'], ARRAY['Changing Rooms','Showers','Lockers','Water Cooler'], 3, 120),
  ('544173', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('544183', 'Badminton Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 6, null),
  ('544183', 'Pickleball Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 8, null),
  ('544185', 'Badminton Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 3, null),
  ('544185', 'Pickleball Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 4, null),
  ('544186', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('544204', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('544261', 'Basketball Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 8, null),
  ('544265', 'Badminton Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 3, null),
  ('544265', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('544265', 'Sepak Takraw Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 5, null),
  ('544584', 'Basketball Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 6, null),
  ('544584', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('544584', 'Gymnasium', ARRAY['Treadmill','Dumbbells','Bench Press','Cable Machine','Stationary Bike'], ARRAY['Changing Rooms','Showers','Lockers','Water Cooler'], 2.5, 90),
  ('544584', 'Swimming Pool', ARRAY[]::text[], ARRAY['Changing Rooms','Showers','Lockers'], 1.5, null),
  ('544584', 'Tennis Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 5, null),
  ('544604', 'Basketball Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 6, null),
  ('544604', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('544604', 'Gymnasium', ARRAY['Treadmill','Dumbbells','Bench Press','Cable Machine','Stationary Bike'], ARRAY['Changing Rooms','Showers','Lockers','Water Cooler'], 2.5, 90),
  ('544604', 'Studio', ARRAY[]::text[], ARRAY['Water Cooler'], null, null),
  ('544604', 'Swimming Pool', ARRAY[]::text[], ARRAY['Changing Rooms','Showers','Lockers'], 2.5, null),
  ('544604', 'Tennis Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 6, null),
  ('544628', 'Gymnasium', ARRAY['Treadmill','Dumbbells','Bench Press','Cable Machine','Stationary Bike'], ARRAY['Changing Rooms','Showers','Lockers','Water Cooler'], 6, 300),
  ('544628', 'Jogging Track', ARRAY[]::text[], ARRAY['Bleachers','Water Cooler','Toilets'], null, null),
  ('544628', 'Swimming Pool', ARRAY[]::text[], ARRAY['Changing Rooms','Showers','Lockers'], 2.5, null),
  ('544628', 'Tennis Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 5, null),
  ('544629', 'Gymnasium', ARRAY['Treadmill','Dumbbells','Bench Press','Cable Machine','Stationary Bike'], ARRAY['Changing Rooms','Showers','Lockers','Water Cooler'], 5, 240),
  ('544629', 'Swimming Pool', ARRAY[]::text[], ARRAY['Changing Rooms','Showers','Lockers'], 2, null),
  ('544649', 'Jogging Track', ARRAY[]::text[], ARRAY['Bleachers','Water Cooler','Toilets'], null, null),
  ('544649', 'Studio', ARRAY[]::text[], ARRAY['Water Cooler'], null, null),
  ('544649', 'Swimming Pool', ARRAY[]::text[], ARRAY['Changing Rooms','Showers','Lockers'], 1.5, null),
  ('544649', 'Tennis Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 6, null),
  ('544692', 'Badminton Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 8, null),
  ('544730', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('544730', 'Gymnasium', ARRAY['Treadmill','Dumbbells','Bench Press','Cable Machine','Stationary Bike'], ARRAY['Changing Rooms','Showers','Lockers','Water Cooler'], 3, 120),
  ('544730', 'Swimming Pool', ARRAY[]::text[], ARRAY['Changing Rooms','Showers','Lockers'], 2, null),
  ('544750', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('544750', 'Gymnasium', ARRAY['Treadmill','Dumbbells','Bench Press','Cable Machine','Stationary Bike'], ARRAY['Changing Rooms','Showers','Lockers','Water Cooler'], 6, 300),
  ('544750', 'Swimming Pool', ARRAY[]::text[], ARRAY['Changing Rooms','Showers','Lockers'], 1.5, null),
  ('544750', 'Tennis Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 4, null),
  ('544774', 'Basketball Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 5, null),
  ('544774', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('544774', 'Gymnasium', ARRAY['Treadmill','Dumbbells','Bench Press','Cable Machine','Stationary Bike'], ARRAY['Changing Rooms','Showers','Lockers','Water Cooler'], 6, 300),
  ('544774', 'Jogging Track', ARRAY[]::text[], ARRAY['Bleachers','Water Cooler','Toilets'], null, null),
  ('544774', 'Studio', ARRAY[]::text[], ARRAY['Water Cooler'], null, null),
  ('544774', 'Swimming Pool', ARRAY[]::text[], ARRAY['Changing Rooms','Showers','Lockers'], 1, null),
  ('544774', 'Tennis Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 6, null),
  ('544799', 'Basketball Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 8, null),
  ('544799', 'Football Field', ARRAY[]::text[], ARRAY['Bleachers','Water Cooler','Toilets'], null, null),
  ('544799', 'Studio', ARRAY[]::text[], ARRAY['Water Cooler'], null, null),
  ('544804', 'Badminton Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 5, null),
  ('544804', 'Basketball Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 6, null),
  ('544804', 'Golf', ARRAY[]::text[], ARRAY['Water Cooler'], null, null),
  ('544804', 'Gymnasium', ARRAY['Treadmill','Dumbbells','Bench Press','Cable Machine','Stationary Bike'], ARRAY['Changing Rooms','Showers','Lockers','Water Cooler'], 2.5, 90),
  ('544804', 'Jogging Track', ARRAY[]::text[], ARRAY['Bleachers','Water Cooler','Toilets'], null, null),
  ('544804', 'Swimming Pool', ARRAY[]::text[], ARRAY['Changing Rooms','Showers','Lockers'], 2, null),
  ('544804', 'Tennis Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 6, null),
  ('544811', 'Gymnasium', ARRAY['Treadmill','Dumbbells','Bench Press','Cable Machine','Stationary Bike'], ARRAY['Changing Rooms','Showers','Lockers','Water Cooler'], 6, 300),
  ('544811', 'Jogging Track', ARRAY[]::text[], ARRAY['Bleachers','Water Cooler','Toilets'], null, null),
  ('544811', 'Swimming Pool', ARRAY[]::text[], ARRAY['Changing Rooms','Showers','Lockers'], 2, null),
  ('544822', 'Basketball Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 5, null),
  ('544822', 'Football Field', ARRAY[]::text[], ARRAY['Bleachers','Water Cooler','Toilets'], null, null),
  ('544822', 'Studio', ARRAY[]::text[], ARRAY['Water Cooler'], null, null),
  ('544823', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('544823', 'Gymnasium', ARRAY['Treadmill','Dumbbells','Bench Press','Cable Machine','Stationary Bike'], ARRAY['Changing Rooms','Showers','Lockers','Water Cooler'], 3, 120),
  ('544823', 'Jogging Track', ARRAY[]::text[], ARRAY['Bleachers','Water Cooler','Toilets'], null, null),
  ('544823', 'Swimming Pool', ARRAY[]::text[], ARRAY['Changing Rooms','Showers','Lockers'], 1.5, null),
  ('544823', 'Tennis Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 8, null),
  ('544823', 'Wall Climbing', ARRAY[]::text[], ARRAY['Water Cooler'], null, null),
  ('544830', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('544830', 'Gymnasium', ARRAY['Treadmill','Dumbbells','Bench Press','Cable Machine','Stationary Bike'], ARRAY['Changing Rooms','Showers','Lockers','Water Cooler'], 4, 180),
  ('544830', 'Swimming Pool', ARRAY[]::text[], ARRAY['Changing Rooms','Showers','Lockers'], 2, null),
  ('544830', 'Tennis Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 8, null),
  ('544834', 'Jogging Track', ARRAY[]::text[], ARRAY['Bleachers','Water Cooler','Toilets'], null, null),
  ('544835', 'Gymnasium', ARRAY['Treadmill','Dumbbells','Bench Press','Cable Machine','Stationary Bike'], ARRAY['Changing Rooms','Showers','Lockers','Water Cooler'], 3, 120),
  ('544916', 'Badminton Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 5, null),
  ('544916', 'Basketball Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 6, null),
  ('544916', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('544916', 'Gymnasium', ARRAY['Treadmill','Dumbbells','Bench Press','Cable Machine','Stationary Bike'], ARRAY['Changing Rooms','Showers','Lockers','Water Cooler'], 2.5, 90),
  ('544916', 'Jogging Track', ARRAY[]::text[], ARRAY['Bleachers','Water Cooler','Toilets'], null, null),
  ('544916', 'Swimming Pool', ARRAY[]::text[], ARRAY['Changing Rooms','Showers','Lockers'], 2.5, null),
  ('544916', 'Tennis Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 6, null),
  ('544964', 'Badminton Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 8, null),
  ('544964', 'Gymnasium', ARRAY['Treadmill','Dumbbells','Bench Press','Cable Machine','Stationary Bike'], ARRAY['Changing Rooms','Showers','Lockers','Water Cooler'], 2.5, 90),
  ('544964', 'Hockey Field', ARRAY[]::text[], ARRAY['Bleachers','Water Cooler','Toilets'], null, null),
  ('544964', 'Pickleball Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 5, null),
  ('544964', 'Studio', ARRAY[]::text[], ARRAY['Water Cooler'], null, null),
  ('544964', 'Swimming Pool', ARRAY[]::text[], ARRAY['Changing Rooms','Showers','Lockers'], 2, null),
  ('544964', 'Table tennis Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 3, null),
  ('544965', 'Badminton Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 4, null),
  ('544969', 'Badminton Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 5, null),
  ('544969', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('544969', 'Football Field', ARRAY[]::text[], ARRAY['Bleachers','Water Cooler','Toilets'], null, null),
  ('544969', 'Gymnasium', ARRAY['Treadmill','Dumbbells','Bench Press','Cable Machine','Stationary Bike'], ARRAY['Changing Rooms','Showers','Lockers','Water Cooler'], 2.5, 90),
  ('544969', 'Netball Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 4, null),
  ('544969', 'Studio', ARRAY[]::text[], ARRAY['Water Cooler'], null, null),
  ('544969', 'Table tennis Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 6, null),
  ('544974', 'Badminton Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 8, null),
  ('544974', 'Basketball Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 3, null),
  ('544974', 'Football Field', ARRAY[]::text[], ARRAY['Bleachers','Water Cooler','Toilets'], null, null),
  ('544974', 'Gymnasium', ARRAY['Treadmill','Dumbbells','Bench Press','Cable Machine','Stationary Bike'], ARRAY['Changing Rooms','Showers','Lockers','Water Cooler'], 4, 180),
  ('544974', 'Netball Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 6, null),
  ('544974', 'Volleyball Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 8, null),
  ('544984', 'Basketball Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 3, null),
  ('544984', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('544984', 'Gymnasium', ARRAY['Treadmill','Dumbbells','Bench Press','Cable Machine','Stationary Bike'], ARRAY['Changing Rooms','Showers','Lockers','Water Cooler'], 4, 180),
  ('544984', 'Swimming Pool', ARRAY[]::text[], ARRAY['Changing Rooms','Showers','Lockers'], 1.5, null),
  ('544984', 'Tennis Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 8, null),
  ('544998', 'Badminton Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 3, null),
  ('544998', 'Basketball Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 4, null),
  ('544998', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('544998', 'Gymnasium', ARRAY['Treadmill','Dumbbells','Bench Press','Cable Machine','Stationary Bike'], ARRAY['Changing Rooms','Showers','Lockers','Water Cooler'], 5, 240),
  ('544998', 'Studio', ARRAY[]::text[], ARRAY['Water Cooler'], null, null),
  ('544998', 'Swimming Pool', ARRAY[]::text[], ARRAY['Changing Rooms','Showers','Lockers'], 1, null),
  ('544998', 'Tennis Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 4, null),
  ('545018', 'Basketball Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 5, null),
  ('545018', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('545018', 'Gymnasium', ARRAY['Treadmill','Dumbbells','Bench Press','Cable Machine','Stationary Bike'], ARRAY['Changing Rooms','Showers','Lockers','Water Cooler'], 6, 300),
  ('545018', 'Swimming Pool', ARRAY[]::text[], ARRAY['Changing Rooms','Showers','Lockers'], 1.5, null),
  ('545018', 'Tennis Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 4, null),
  ('545025', 'Badminton Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 5, null),
  ('545025', 'Basketball Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 6, null),
  ('545025', 'Pickleball Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 8, null),
  ('545025', 'Studio', ARRAY[]::text[], ARRAY['Water Cooler'], null, null),
  ('545025', 'Table Tennis Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 4, null),
  ('545025', 'Tennis Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 5, null),
  ('545041', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('545041', 'Gymnasium', ARRAY['Treadmill','Dumbbells','Bench Press','Cable Machine','Stationary Bike'], ARRAY['Changing Rooms','Showers','Lockers','Water Cooler'], 6, 300),
  ('545041', 'Swimming Pool', ARRAY[]::text[], ARRAY['Changing Rooms','Showers','Lockers'], 2.5, null),
  ('545041', 'Tennis Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 4, null),
  ('545064', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('545064', 'Gymnasium', ARRAY['Treadmill','Dumbbells','Bench Press','Cable Machine','Stationary Bike'], ARRAY['Changing Rooms','Showers','Lockers','Water Cooler'], 5, 240),
  ('545064', 'Table Tennis Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 8, null),
  ('545076', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('545076', 'Gymnasium', ARRAY['Treadmill','Dumbbells','Bench Press','Cable Machine','Stationary Bike'], ARRAY['Changing Rooms','Showers','Lockers','Water Cooler'], 3, 120),
  ('545076', 'Studio', ARRAY[]::text[], ARRAY['Water Cooler'], null, null),
  ('545076', 'Swimming Pool', ARRAY[]::text[], ARRAY['Changing Rooms','Showers','Lockers'], 2.5, null),
  ('545076', 'Table Tennis Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 8, null),
  ('545076', 'Tennis Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 3, null),
  ('545078', 'Gymnasium', ARRAY['Treadmill','Dumbbells','Bench Press','Cable Machine','Stationary Bike'], ARRAY['Changing Rooms','Showers','Lockers','Water Cooler'], 3, 120),
  ('545078', 'Swimming Pool', ARRAY[]::text[], ARRAY['Changing Rooms','Showers','Lockers'], 2.5, null),
  ('545079', 'Football Field', ARRAY[]::text[], ARRAY['Bleachers','Water Cooler','Toilets'], null, null),
  ('545081', 'Badminton Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 8, null),
  ('545081', 'Basketball Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 3, null),
  ('545081', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('545081', 'Football Field', ARRAY[]::text[], ARRAY['Bleachers','Water Cooler','Toilets'], null, null),
  ('545081', 'Gymnasium', ARRAY['Treadmill','Dumbbells','Bench Press','Cable Machine','Stationary Bike'], ARRAY['Changing Rooms','Showers','Lockers','Water Cooler'], 5, 240),
  ('545081', 'Netball Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 8, null),
  ('545081', 'Shooting Range', ARRAY[]::text[], ARRAY['Water Cooler'], null, null),
  ('545081', 'Table Tennis Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 4, null),
  ('545081', 'Volleyball Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 5, null),
  ('545082', 'Gymnasium', ARRAY['Treadmill','Dumbbells','Bench Press','Cable Machine','Stationary Bike'], ARRAY['Changing Rooms','Showers','Lockers','Water Cooler'], 5, 240),
  ('545082', 'Studio', ARRAY[]::text[], ARRAY['Water Cooler'], null, null),
  ('545082', 'Swimming Pool', ARRAY[]::text[], ARRAY['Changing Rooms','Showers','Lockers'], 1, null),
  ('545082', 'Tennis Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 4, null),
  ('545083', 'Football Field', ARRAY[]::text[], ARRAY['Bleachers','Water Cooler','Toilets'], null, null),
  ('545085', 'Gymnasium', ARRAY['Treadmill','Dumbbells','Bench Press','Cable Machine','Stationary Bike'], ARRAY['Changing Rooms','Showers','Lockers','Water Cooler'], 5, 240),
  ('545085', 'Swimming Pool', ARRAY[]::text[], ARRAY['Changing Rooms','Showers','Lockers'], 1, null),
  ('545085', 'Tennis Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 3, null),
  ('545088', 'Badminton Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 4, null),
  ('545088', 'Basketball Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 5, null),
  ('545088', 'Football Field', ARRAY[]::text[], ARRAY['Bleachers','Water Cooler','Toilets'], null, null),
  ('545088', 'Studio', ARRAY[]::text[], ARRAY['Water Cooler'], null, null),
  ('545090', 'Badminton Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 3, null),
  ('545090', 'Basketball Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 4, null),
  ('545090', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('545090', 'Football Field', ARRAY[]::text[], ARRAY['Bleachers','Water Cooler','Toilets'], null, null),
  ('545090', 'Gymnasium', ARRAY['Treadmill','Dumbbells','Bench Press','Cable Machine','Stationary Bike'], ARRAY['Changing Rooms','Showers','Lockers','Water Cooler'], 6, 300),
  ('545090', 'Studio', ARRAY[]::text[], ARRAY['Water Cooler'], null, null),
  ('545090', 'Table Tennis Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 4, null),
  ('545090', 'Volleyball Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 5, null),
  ('545090', 'Wall Climbing', ARRAY[]::text[], ARRAY['Water Cooler'], null, null),
  ('545091', 'Badminton Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 8, null),
  ('545091', 'Basketball Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 3, null),
  ('545091', 'Football Field', ARRAY[]::text[], ARRAY['Bleachers','Water Cooler','Toilets'], null, null),
  ('545091', 'Netball Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 5, null),
  ('545091', 'Volleyball Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 6, null),
  ('545092', 'Football Field', ARRAY[]::text[], ARRAY['Bleachers','Water Cooler','Toilets'], null, null),
  ('545092', 'Jogging Track', ARRAY[]::text[], ARRAY['Bleachers','Water Cooler','Toilets'], null, null),
  ('545092', 'Studio', ARRAY[]::text[], ARRAY['Water Cooler'], null, null),
  ('545119', 'Badminton Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 5, null),
  ('545119', 'Basketball Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 6, null),
  ('545119', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('545119', 'Gymnasium', ARRAY['Treadmill','Dumbbells','Bench Press','Cable Machine','Stationary Bike'], ARRAY['Changing Rooms','Showers','Lockers','Water Cooler'], 2.5, 90),
  ('545119', 'Swimming Pool', ARRAY[]::text[], ARRAY['Changing Rooms','Showers','Lockers'], 2.5, null),
  ('545119', 'Tennis Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 5, null),
  ('545123', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('545166', 'Badminton Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 8, null),
  ('545166', 'Basketball Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 3, null),
  ('545166', 'Football Field', ARRAY[]::text[], ARRAY['Bleachers','Water Cooler','Toilets'], null, null),
  ('545166', 'Jogging Track', ARRAY[]::text[], ARRAY['Bleachers','Water Cooler','Toilets'], null, null),
  ('545166', 'Studio', ARRAY[]::text[], ARRAY['Water Cooler'], null, null),
  ('545166', 'Volleyball Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 8, null),
  ('545166', 'Wall Climbing', ARRAY[]::text[], ARRAY['Water Cooler'], null, null),
  ('545267', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('545283', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('545523', 'Gymnasium', ARRAY['Treadmill','Dumbbells','Bench Press','Cable Machine','Stationary Bike'], ARRAY['Changing Rooms','Showers','Lockers','Water Cooler'], 5, 240),
  ('545523', 'Swimming Pool', ARRAY[]::text[], ARRAY['Changing Rooms','Showers','Lockers'], 1, null),
  ('545535', 'Gymnasium', ARRAY['Treadmill','Dumbbells','Bench Press','Cable Machine','Stationary Bike'], ARRAY['Changing Rooms','Showers','Lockers','Water Cooler'], 2.5, 90),
  ('545550', 'Gymnasium', ARRAY['Treadmill','Dumbbells','Bench Press','Cable Machine','Stationary Bike'], ARRAY['Changing Rooms','Showers','Lockers','Water Cooler'], 3, 120),
  ('545550', 'Swimming Pool', ARRAY[]::text[], ARRAY['Changing Rooms','Showers','Lockers'], 2.5, null),
  ('545552', 'Swimming Pool', ARRAY[]::text[], ARRAY['Changing Rooms','Showers','Lockers'], 1, null),
  ('545552', 'Table tennis Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 8, null),
  ('545653', 'Gymnasium', ARRAY['Treadmill','Dumbbells','Bench Press','Cable Machine','Stationary Bike'], ARRAY['Changing Rooms','Showers','Lockers','Water Cooler'], 2.5, 90),
  ('545653', 'Swimming Pool', ARRAY[]::text[], ARRAY['Changing Rooms','Showers','Lockers'], 2.5, null),
  ('545677', 'Athletics Track', ARRAY[]::text[], ARRAY['Bleachers','Water Cooler','Toilets'], null, null),
  ('545677', 'Football Field', ARRAY[]::text[], ARRAY['Bleachers','Water Cooler','Toilets'], null, null),
  ('545678', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('545678', 'Gymnasium', ARRAY['Treadmill','Dumbbells','Bench Press','Cable Machine','Stationary Bike'], ARRAY['Changing Rooms','Showers','Lockers','Water Cooler'], 2.5, 90),
  ('545678', 'Swimming Pool', ARRAY[]::text[], ARRAY['Changing Rooms','Showers','Lockers'], 1, null),
  ('545679', 'Gymnasium', ARRAY['Treadmill','Dumbbells','Bench Press','Cable Machine','Stationary Bike'], ARRAY['Changing Rooms','Showers','Lockers','Water Cooler'], 4, 180),
  ('545679', 'Swimming Pool', ARRAY[]::text[], ARRAY['Changing Rooms','Showers','Lockers'], 2, null),
  ('545708', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('545708', 'Swimming Pool', ARRAY[]::text[], ARRAY['Changing Rooms','Showers','Lockers'], 1, null),
  ('545779', 'Squash Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 4, null),
  ('545779', 'Swimming Pool', ARRAY[]::text[], ARRAY['Changing Rooms','Showers','Lockers'], 2, null),
  ('545782', 'Swimming Pool', ARRAY[]::text[], ARRAY['Changing Rooms','Showers','Lockers'], 2.5, null),
  ('546013', 'Swimming Pool', ARRAY[]::text[], ARRAY['Changing Rooms','Showers','Lockers'], 1, null),
  ('546018', 'Gymnasium', ARRAY['Treadmill','Dumbbells','Bench Press','Cable Machine','Stationary Bike'], ARRAY['Changing Rooms','Showers','Lockers','Water Cooler'], 2.5, 90),
  ('546018', 'Swimming Pool', ARRAY[]::text[], ARRAY['Changing Rooms','Showers','Lockers'], 2, null),
  ('546032', 'Gymnasium', ARRAY['Treadmill','Dumbbells','Bench Press','Cable Machine','Stationary Bike'], ARRAY['Changing Rooms','Showers','Lockers','Water Cooler'], 4, 180),
  ('546032', 'Swimming Pool', ARRAY[]::text[], ARRAY['Changing Rooms','Showers','Lockers'], 1, null),
  ('546066', 'Swimming Pool', ARRAY[]::text[], ARRAY['Changing Rooms','Showers','Lockers'], 1.5, null),
  ('546134', 'Swimming Pool', ARRAY[]::text[], ARRAY['Changing Rooms','Showers','Lockers'], 2, null),
  ('546195', 'Swimming Pool', ARRAY[]::text[], ARRAY['Changing Rooms','Showers','Lockers'], 2.5, null),
  ('546200', 'Gymnasium', ARRAY['Treadmill','Dumbbells','Bench Press','Cable Machine','Stationary Bike'], ARRAY['Changing Rooms','Showers','Lockers','Water Cooler'], 4, 180),
  ('546200', 'Swimming Pool', ARRAY[]::text[], ARRAY['Changing Rooms','Showers','Lockers'], 1.5, null),
  ('546242', 'Swimming Pool', ARRAY[]::text[], ARRAY['Changing Rooms','Showers','Lockers'], 2, null),
  ('546256', 'Gymnasium', ARRAY['Treadmill','Dumbbells','Bench Press','Cable Machine','Stationary Bike'], ARRAY['Changing Rooms','Showers','Lockers','Water Cooler'], 2.5, 90),
  ('546256', 'Swimming Pool', ARRAY[]::text[], ARRAY['Changing Rooms','Showers','Lockers'], 1, null),
  ('546290', 'Golf', ARRAY[]::text[], ARRAY['Water Cooler'], null, null),
  ('546290', 'Gymnasium', ARRAY['Treadmill','Dumbbells','Bench Press','Cable Machine','Stationary Bike'], ARRAY['Changing Rooms','Showers','Lockers','Water Cooler'], 5, 240),
  ('546290', 'Studio', ARRAY[]::text[], ARRAY['Water Cooler'], null, null),
  ('546290', 'Swimming Pool', ARRAY[]::text[], ARRAY['Changing Rooms','Showers','Lockers'], 1, null),
  ('546402', 'Basketball Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 4, null),
  ('546402', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('546430', 'Gymnasium', ARRAY['Treadmill','Dumbbells','Bench Press','Cable Machine','Stationary Bike'], ARRAY['Changing Rooms','Showers','Lockers','Water Cooler'], 5, 240),
  ('546430', 'Swimming Pool', ARRAY[]::text[], ARRAY['Changing Rooms','Showers','Lockers'], 1, null),
  ('546433', 'Gymnasium', ARRAY['Treadmill','Dumbbells','Bench Press','Cable Machine','Stationary Bike'], ARRAY['Changing Rooms','Showers','Lockers','Water Cooler'], 2.5, 90),
  ('546433', 'Swimming Pool', ARRAY[]::text[], ARRAY['Changing Rooms','Showers','Lockers'], 2, null),
  ('546684', 'Swimming Pool', ARRAY[]::text[], ARRAY['Changing Rooms','Showers','Lockers'], 2.5, null),
  ('546684', 'Tennis Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 6, null),
  ('546693', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('546693', 'Gymnasium', ARRAY['Treadmill','Dumbbells','Bench Press','Cable Machine','Stationary Bike'], ARRAY['Changing Rooms','Showers','Lockers','Water Cooler'], 2.5, 90),
  ('546693', 'Swimming Pool', ARRAY[]::text[], ARRAY['Changing Rooms','Showers','Lockers'], 2.5, null),
  ('546773', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('546776', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('546776', 'Gymnasium', ARRAY['Treadmill','Dumbbells','Bench Press','Cable Machine','Stationary Bike'], ARRAY['Changing Rooms','Showers','Lockers','Water Cooler'], 6, 300),
  ('546776', 'Jogging Track', ARRAY[]::text[], ARRAY['Bleachers','Water Cooler','Toilets'], null, null),
  ('546776', 'Swimming Pool', ARRAY[]::text[], ARRAY['Changing Rooms','Showers','Lockers'], 1, null),
  ('546896', 'Cue Sports Table', ARRAY[]::text[], ARRAY['Water Cooler'], null, null),
  ('546920', 'Gymnasium', ARRAY['Treadmill','Dumbbells','Bench Press','Cable Machine','Stationary Bike'], ARRAY['Changing Rooms','Showers','Lockers','Water Cooler'], 5, 240),
  ('546920', 'Swimming Pool', ARRAY[]::text[], ARRAY['Changing Rooms','Showers','Lockers'], 2.5, null),
  ('546953', 'Swimming Pool', ARRAY[]::text[], ARRAY['Changing Rooms','Showers','Lockers'], 1, null),
  ('547200', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('547289', 'Gymnasium', ARRAY['Treadmill','Dumbbells','Bench Press','Cable Machine','Stationary Bike'], ARRAY['Changing Rooms','Showers','Lockers','Water Cooler'], 4, 180),
  ('547289', 'Swimming Pool', ARRAY[]::text[], ARRAY['Changing Rooms','Showers','Lockers'], 2.5, null),
  ('547289', 'Tennis Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 8, null),
  ('547312', 'Gymnasium', ARRAY['Treadmill','Dumbbells','Bench Press','Cable Machine','Stationary Bike'], ARRAY['Changing Rooms','Showers','Lockers','Water Cooler'], 2.5, 90),
  ('547312', 'Swimming Pool', ARRAY[]::text[], ARRAY['Changing Rooms','Showers','Lockers'], 2, null),
  ('547315', 'Gymnasium', ARRAY['Treadmill','Dumbbells','Bench Press','Cable Machine','Stationary Bike'], ARRAY['Changing Rooms','Showers','Lockers','Water Cooler'], 4, 180),
  ('547315', 'Swimming Pool', ARRAY[]::text[], ARRAY['Changing Rooms','Showers','Lockers'], 1, null),
  ('547315', 'Tennis Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 8, null),
  ('547453', 'Basketball Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 3, null),
  ('547529', 'Badminton Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 4, null),
  ('547529', 'Basketball Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 5, null),
  ('547529', 'Football Field', ARRAY[]::text[], ARRAY['Bleachers','Water Cooler','Toilets'], null, null),
  ('547529', 'Gymnasium', ARRAY['Treadmill','Dumbbells','Bench Press','Cable Machine','Stationary Bike'], ARRAY['Changing Rooms','Showers','Lockers','Water Cooler'], 6, 300),
  ('547529', 'Netball Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 3, null),
  ('547529', 'Studio', ARRAY[]::text[], ARRAY['Water Cooler'], null, null),
  ('547529', 'Volleyball Court', ARRAY['Nets','Court Lighting','Scoreboard'], ARRAY['Booking Counter','Water Cooler'], 5, null),
  ('547766', 'Swimming Pool', ARRAY[]::text[], ARRAY['Changing Rooms','Showers','Lockers'], 2, null),
  ('547791', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('547791', 'Gymnasium', ARRAY['Treadmill','Dumbbells','Bench Press','Cable Machine','Stationary Bike'], ARRAY['Changing Rooms','Showers','Lockers','Water Cooler'], 2.5, 90),
  ('547791', 'Studio', ARRAY[]::text[], ARRAY['Water Cooler'], null, null),
  ('547791', 'Swimming Pool', ARRAY[]::text[], ARRAY['Changing Rooms','Showers','Lockers'], 2, null),
  ('547803', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('547803', 'Gymnasium', ARRAY['Treadmill','Dumbbells','Bench Press','Cable Machine','Stationary Bike'], ARRAY['Changing Rooms','Showers','Lockers','Water Cooler'], 6, 300),
  ('547803', 'Swimming Pool', ARRAY[]::text[], ARRAY['Changing Rooms','Showers','Lockers'], 1.5, null),
  ('547810', 'Swimming Pool', ARRAY[]::text[], ARRAY['Changing Rooms','Showers','Lockers'], 2, null),
  ('547819', 'Swimming Pool', ARRAY[]::text[], ARRAY['Changing Rooms','Showers','Lockers'], 2.5, null),
  ('547822', 'Swimming Pool', ARRAY[]::text[], ARRAY['Changing Rooms','Showers','Lockers'], 1, null),
  ('547962', 'Fitness Corner', ARRAY['Pull-up Bars','Parallel Bars','Sit-up Bench'], ARRAY['Water Cooler','Shelter'], null, null),
  ('547962', 'Swimming Pool', ARRAY[]::text[], ARRAY['Changing Rooms','Showers','Lockers'], 2, null),
  ('548086', 'Gymnasium', ARRAY['Treadmill','Dumbbells','Bench Press','Cable Machine','Stationary Bike'], ARRAY['Changing Rooms','Showers','Lockers','Water Cooler'], 3, 120),
  ('548086', 'Swimming Pool', ARRAY[]::text[], ARRAY['Changing Rooms','Showers','Lockers'], 1, null),
  ('548102', 'Swimming Pool', ARRAY[]::text[], ARRAY['Changing Rooms','Showers','Lockers'], 1.5, null),
  ('548131', 'Swimming Pool', ARRAY[]::text[], ARRAY['Changing Rooms','Showers','Lockers'], 2, null),
  ('548173', 'Swimming Pool', ARRAY[]::text[], ARRAY['Changing Rooms','Showers','Lockers'], 2.5, null),
  ('548177', 'Gymnasium', ARRAY['Treadmill','Dumbbells','Bench Press','Cable Machine','Stationary Bike'], ARRAY['Changing Rooms','Showers','Lockers','Water Cooler'], 3, 120),
  ('548177', 'Swimming Pool', ARRAY[]::text[], ARRAY['Changing Rooms','Showers','Lockers'], 1.5, null),
  ('548178', 'Gymnasium', ARRAY['Treadmill','Dumbbells','Bench Press','Cable Machine','Stationary Bike'], ARRAY['Changing Rooms','Showers','Lockers','Water Cooler'], 5, 240),
  ('548178', 'Swimming Pool', ARRAY[]::text[], ARRAY['Changing Rooms','Showers','Lockers'], 2.5, null)
on conflict (postal_code, facility_type) do update
set
  equipment = excluded.equipment,
  amenities = excluded.amenities,
  day_pass_price = excluded.day_pass_price,
  membership_price = excluded.membership_price;
